### ISSUE TITLE
Create report even when stopped

### ISSUE THREAD

**Issue by kolloch** [gatling/gatling#1386]
When interrupting a simulation with Ctrl+C or a kill, no report is generated.

Also the simulation.log is empty or incomplete.

It would be really nice, if gatling would just proceed writing a report for the gathered data so far when interrupted.

Possible Workaround (not tried): Use reporting to graphite etc.

**Comment by emtammaru** [comment]
I would argue this is a defect not a feature request, because there's a note specifically about this "feature" in the reports documentation:

https://gatling.io/docs/2.3/general/reports/

![screen shot 2018-04-30 at 5 16 35 pm](https://user-images.githubusercontent.com/14222797/39456279-4300f730-4c9a-11e8-8452-d600ac185f4d.png)


Ctrl+C does not leave any simulation.log behind from which to generate a report.  please update the docs to reflect this at least. . .

**Comment by slandelle** [comment]
@emtammaru I've improved the doc but that's the best we'll do ourselves: https://github.com/gatling/gatling/commit/9ca3a655c2fc2a6b16d42d4acfe10f8b652ee5b6. Like I said in previous comment, contributions welcome.
