### ISSUE TITLE
HTTP: response time measurement omits time to connect and send request

### ISSUE THREAD

**Issue by ceeaspb** [gatling/gatling#2077]
in 2.0 RC2 (likely the same for all previous versions):
running the simple coordinated omission test of @giltene, Gatling does not capture the server system freeze in the response time percentiles.

eg. I run the following wrk test:

```
$ wrk --latency -d 10s -t 1 -c 1 "<url>"
Running 10s test @ <url>
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.67s     2.93s    6.01s    61.09%
    Req/Sec   592.26    746.02     1.67k    62.88%
  Latency Distribution
     50%    6.01s 
     75%    6.01s 
     90%    6.01s 
     99%    6.01s 
  5760 requests in 10.00s, 2.04MB read
  Socket errors: connect 0, read 0, write 0, timeout 2
```

and freeze the server for 6 seconds:

```
kill -TSTP 7090;sleep 6;kill -CONT 7090
```

we can see from the above that the median is calculated correctly.

when running the following workload similar to wrk above:

```
constantUsersPerSec(500) during(10 seconds)
```

the measurements are not capturing the server freeze.

```
---- Global Information --------------------------------------------------------
> request count                                       5000 (OK=4981   KO=19    )
> min response time                                      1 (OK=1      KO=554   )
> max response time                                   6017 (OK=6017   KO=995   )
> mean response time                                   135 (OK=132    KO=715   )
> std deviation                                        829 (OK=830    KO=147   )
> response time 50th percentile                         10 (OK=10     KO=631   )
> response time 90th percentile                         38 (OK=37     KO=958   )
> mean requests/sec                                  299.7 (OK=298.5  KO=1.14  )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                          4881 ( 98%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                          100 (  2%)
> failed                                                19 (  0%)
---- Errors --------------------------------------------------------------------
> java.net.ConnectException: Connection reset by peer to http://     19 (100.0%)
<url>

```

I suspect this may be because the measurement is not started before the connection is initiated? I haven't looked at the code yet.

**Comment by glennmartinez** [comment]
Is Gatling's response time = to responseEnd? or is it timeToLastByte?

**Comment by slandelle** [comment]
@glennmartinez http://gatling.io/docs/2.1.7/general/timings.html#response-time

**Comment by tacoben** [comment]
question:   does this mean that CO is now resolved in gatling for high load?  or does it mean that high load scenarios CO is still an issue... im having some trouble figuring this out from the comments.

**Comment by slandelle** [comment]
@tacoben Maybe @giltene will disagree on this and will want to correct me, but here's my take:

CO is a (load test design / load test tool implementation) issue.
The root cause is that you might be introducing an artificial coordination between the client (the load test run) and the server (the system under test).

This happens when you try to execute a bunch of unrelated requests sequentially into a loop (or multiple concurrent loops). If the system under test starts lagging, the next request won't be started in due time.

IMO, the root cause here is: "why were those unrelated requests executed sequentially in the first place???". Those should have been scheduled independently!

Beware that it's your job to figure out if your requests are unrelated or not. For example:
* the tons of orders executed in a HFT system are probably unrelated
* requests from different virtual users on a website are usually unrelated
* requests from a given virtual user on a website are definitively *related*: a human won't proceed to the next page before he has received the first one!

This CO issue looks very similar to me to the [difference between closed and open workload models](http://gatling.io/docs/2.1.7/general/simulation_setup.html#injection).

In a closed model, you only have a given number of users in your system, and a new user can't enter the system until another one exits.
This model is unrealistic in most cases. It's only valid when you have a queue in front of your system that allows your users to actually enter.
So far, I've only seen this kind of application in some ticketing platforms: when there's too many customers, you can't buy until your number is called.
The consequence of this model is that throughput drops when latency increases, so the test "self heals".

In most system, you want an open workload, where new users keep on arriving whatever your latency, possibly causing your system under test to crash.

Back to Gatling: Gatling emphasizes open workload model: you schedule the virtual users arrival rate.

If you really want a closed workload model, you can do what most other tools do: wrap your scenario into a loop, and reset your virtual users on each iteration.
