### ISSUE TITLE
Statistics: mode

### ISSUE THREAD

**Issue by WillerZ** [gatling/gatling#2475]
This is not a bug.

Gatling reports include the mean, standard-deviation, median (as 50th percentile), and other percentiles which can be directly measured. I would like to calculate the mode of the underlying distribution as well. This, and other non-directly-measurable statistical properties, require that we know what the underlying distribution function is.

Every test I've run with Gatling yields a response time distribution graph which looks very much as though it is a log-normal distribution. I have some reasons for thinking that this should be true for the systems I'm testing, but I do not have a sound reason to think that this should (or indeed should not) be true for anyone else's systems.

Are you open to a pull-request that calculates the mode on the basis that the underlying distribution is a log-normal distribution?

**Comment by slandelle** [comment]
Could you elaborate on how modes would help you characterize performance, please?
Also, why do you need to assume a log-normal distribution?

**Comment by slandelle** [comment]
@WillerZ ping

**Comment by WillerZ** [comment]
The more I think about this the less I think I need it in the stats module; if I want to model my stuff as log-normal I only need the arithmetic mean and variance (both of which I can already get fairly directly) and then I am not in the position of implying that anyone else's results should conform to an underlying log-normal distribution.

I therefore close this ticket and apologise for wasting your time.

**Comment by slandelle** [comment]
No problem

**Comment by philippe-tr** [comment]
My data very much appears to fit a log normal distribution. I wish the response times columns in the table made available the geometric mean and geometric standard deviation instead of arithmetic mean and arithmetic standard deviation. See http://www.lognormal.com/blog/2012/08/13/analysing-performance-data/ for a discussion on this.

I also wish I could see all the response times plotted on a distribution curve. That would help validate the distribution of the data.
