### ISSUE TITLE
HTTP: Improve logback.xml so response bodies are not discarded on debug

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2509]
Currently, you actually have to enable DEBUG on `io.gatling.http.response`.

**Comment by convenient** [comment]
I was reviewing the [logback.xml documentation](http://gatling.io/docs/2.1.3/general/configuration.html?highlight=logback
) in preparation for a commit when I noticed that the link for '[default logging configuration file](https://github.com/gatling/gatling/blob/master/gatling-bundle/src/universal/conf/logback.xml)' was broken because the `logback.xml` file no longer exists.

I believe it may have been removed when `logback.xml` was added to the gitignore in #2450

Since the file will no longer exist in the repo, and we don't really want to be pointing people to the .dummy file, do you think it would be sufficient to tell people the path of the file `conf/logback.xml`?

**Comment by slandelle** [comment]
Actually, the link should point to the dummy file. It renamed when it's packaged during [build](https://github.com/gatling/gatling/blob/master/project/CopyLogback.scala#L12).

**Comment by slandelle** [comment]
Fixed in #2512, thanks for reporting!
