### ISSUE TITLE
"unhandled event Run in state WaitingToStart"

### ISSUE THREAD

**Issue by Maxwell2022** [gatling/gatling#2619]
When I try to run a simple simulation I get the following message and nothing is happening:

```bash
user@ubuntu:~/gatling-test$ ./bin/gatling.sh 
GATLING_HOME is set to /home/user/gatling-test
Choose a simulation number:
     [0] computerdatabase.BasicSimulation
     [1] computerdatabase.advanced.AdvancedSimulationStep01
     [2] computerdatabase.advanced.AdvancedSimulationStep02
     [3] computerdatabase.advanced.AdvancedSimulationStep03
     [4] computerdatabase.advanced.AdvancedSimulationStep04
     [5] computerdatabase.advanced.AdvancedSimulationStep05
     [6] packageName.MyTestSimulation
6
Select simulation id (default is 'mytestsimulation'). Accepted characters are a-z, A-Z, 0-9, - and _

Select run description (optional)

Simulation packageName.MyTestSimulation started...
[WARN] [03/17/2015 11:36:28.664] [GatlingSystem-akka.actor.default-dispatcher-4] [akka://GatlingSystem/user/gatling-controller] unhandled event Run in state WaitingToStart
```

**Comment by slandelle** [comment]
You grabbed the wrong bundle. We had an issue with our build system a few days ago that published artifacts with a SNAPSHOT suffix instead of a timestamp. Those versions were indeed broken.
Things went back to normal and proper timestamped artifacts with newer modification dates were published, but those broken artifacts still lingered.
We're in the process of cleaning up so people don't get confused.

**Comment by Maxwell2022** [comment]
cool, I'm now using `2.1.4` and did get any issue. Thanks for the update

**Comment by slandelle** [comment]
The issue was caused by a mistake in a refactoring in upcoming 2.2.0.
