### ISSUE TITLE
Core: Use Caffeine for LRU cache when we'll migrate to JDK8.

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2620]
https://github.com/ben-manes/caffeine

**Comment by nremond** [comment]
Didn't know about it, cool lib !

**Comment by slandelle** [comment]
http://stackoverflow.com/questions/29084088/synchronous-in-memory-lru-cache-map/29087095

**Comment by ben-manes** [comment]
fyi,

From your closed tickets it looks like CLHM caused some pain due to expensive initialization and large footprint. That was due to its striped ring buffers to maximize throughput, where there are ~ 4 * CPUs stripes. That also added a slight sequential penalty of iterating over unused stripes when draining the buffers.

Caffeine uses dynamic resizing based on contention. The initial footprint is now ~600 bytes and lazily grows to meet throughput demands. It uses an adaption of j.u.c.Striped64, the basis for Java's high speed 64-bit atomic counters (e.g. `LongAdder`).

Hopefully that solves the underlying problem that caused Gatling to be selective of where to use CLHM.

**Comment by slandelle** [comment]
Hi Ben,

Thanks a lot for the explanations (and for all your amazing work)!

We use CLHM for some per virtual user caches and the biggest issue was that we were eagerly creating them, hurting high throughput use cases that don't actually need them.

But still, getting more memory efficient LRU or LFU caches would definitively be a huge improvement.

Next Gatling version (2.3) will still target JDK7, but that we'll target JDK8 afterward. I can't wait to be playing with Caffeine!

**Comment by blemale** [comment]
FYI, I just release a thin Scala wrapper for Caffeine: https://github.com/blemale/scaffeine.
It could ease integration of Caffeine in a Scala code base.

**Comment by slandelle** [comment]
Thanks for the ping.
We've decided to go with JDK8 for 2.2, but couldn't find time to investigate yet :(

**Comment by slandelle** [comment]
@blemale In your opinion, what would a suited replacement for ConcurrentLinkedHashMap be with Caffeine?
