### ISSUE TITLE
Failure at unexpected request rate

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#2682]
Hi, 

When we run this test ( https://github.com/bbc/gatling-load-tests/blob/master/src/test/scala/bbc/news/Newsbeat.scala ) on a m3.xlarge, we hit a peak of 500 RPS and then there is a massive spike in response times. I have measured the heap and GC at this point using jvmtop and there is no unusual GC activity and the heap is around 2GB ("-Xmx12G").

We curled the URLs at this point and there were still fast response times. We ran the same test in SOASTA CloudTest and we managed a peak request rate of 2700/sec and then we receive errors. I am unsure on what the issue is, but until we find out I'll have trouble using Gatling again. 

Many Thanks

Aidy

**Comment by slandelle** [comment]
Could you please upgrade to 2.1.5. We haven't made the announcement yet, but the artifacts are already available on maven central.

Then, are you sure you're not comparing apples and oranges, and that SOASTA doesn't share connections amongst virtual users?

**Comment by slandelle** [comment]
Also, do you have one server, or is it actually a cluster behind some DNS round robin?

**Comment by aidylewis** [comment]
@slandelle There is no connection pooling in SOASTA CT, we tried connection pooling with Gatling and still the same issue.

**Comment by slandelle** [comment]
OK, so what about DNS round robin, then?

**Comment by aidylewis** [comment]
Running from one box within an Amazon VPC the application is running behind ELB and I have set '"-Dsun.net.inetaddr.ttl=0"' to prevent DNS caching.

**Comment by slandelle** [comment]
Have you tried removing resource inferring? That's pretty expensive.

**Comment by aidylewis** [comment]
Yes, but I'll try it again with 2.1.5. What version of Scala do you suggest with 2.1.5?

**Comment by slandelle** [comment]
You can use Scala 2.11.6 but I don't expect any improvement there.

**Comment by aidylewis** [comment]
Regarding DNS, there are four IP addresses associated with the host being tested, all of which are returned for every DNS lookup. Those four IP addresses each correspond to a caching HTTP load balancer.

Since there are only seven URLs under test, and all of them are publicly cacheable with max-age=60, the majority of the load is handled by the RAM-based cache on the load balancers.

For requests that "miss" the load balancer cache, they are proxied through a series of layers, ultimately ending up in an EC2 ASG. We can see brief blips in response times every minute for each URL, corresponding to the cache misses, but that's orders of magnitude less significant that the problem we see at ~500r/s.

**Comment by ceeaspb** [comment]
Hi Aidy,

so couple of things off the top of my head, I would want to get the
environment refined before looking at Gatling itself :
I am ignoring whether you have any hourly budget for the AWS vms...

1) AWS m3 instance is a general purpose instance. I use c4 as a minimum
spec for the instance type when volume testing assuming you don't want the
client to be a bottleneck.

Then there is the instance "size" - increasing the instance size also
improves the network performance (bandwidth and likely latency). With
xlarge you are already at "high".

2) Then there is the Image type - what AMI ID are you using?
a) type PV or HVM?
You'll want to be on HVM , epoll may (likely) struggle with high throughput
on a PV image, because every time it makes a system call it will being
going through/via xen hypervisor calls instead of directly to the bare
metal.
Being on a C4 instance also conveniently forces you onto an HVM image type
so you can't be on the less efficient image type.

http://aws.amazon.com/amazon-linux-ami/instance-type-matrix/

b) enhanced networking enabled:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enable-enhanced-networking

You'll want this enabled where possible... if you use an amazon Linux AMI
on C3/4 (+in a vpc...) then it already enabled for you...



3) You have provided some things that you have checked but there could be
lots of other possibilities.
Could you cover off some high level possible causes:
Are you out of X resource?
where X is:
cpu (5 intervals of vmstat output will help some basic investigation)
network
disk io
memory (os memory/ swapping)

Identifying which are the main culprits will direct investigations.
There are some further diag's that could be taken but cover off the above
first.

Thanks!
Alex

**Comment by pdalpra** [comment]
Just did a run on m3.2xlarge, using Gatling 2.1.5.
BUT only with the last injection step, e.g. constantUsersPerSec(400)... see
the results below.
Many of the KOs are caused by *ConnectException*s, when users starts to
pile up and network is either saturated or we get blocked by Amazon,
thinking we're DOSing the BBC :)
But still, you can see that Gatling achieves 2700 requests/s.

My 2 cents : the injection profile you use on SOASTA and Gatling are not
equivalent.

================================================================================
---- Global Information
--------------------------------------------------------
> request count                                     105947 (OK=77918
 KO=28029 )
> min response time                                      0 (OK=18     KO=0
    )
> max response time                                  12017 (OK=12017
 KO=5706  )
> mean response time                                   601 (OK=817    KO=1
    )
> std deviation                                        869 (OK=921    KO=92
   )
> response time 50th percentile                        215 (OK=534    KO=0
    )
> response time 75th percentile                        921 (OK=1202   KO=0
    )
> mean requests/sec                                2779.375 (OK=2044.073
KO=735.303)

**Comment by pdalpra** [comment]
Just did a run on m3.2xlarge, using Gatling 2.1.5.
BUT only with the last injection step, e.g. constantUsersPerSec(400)... see
the results below.
Many of the KOs are caused by *ConnectException*s, when users starts to
pile up and network is either saturated or we get blocked by Amazon,
thinking we're DOSing the BBC :)
But still, you can see that Gatling achieves 2700 requests/s.

My 2 cents : the injection profile you use on SOASTA and Gatling are not
equivalent.

```
---- Global Information --------------------------------------------------------
> request count                                     105947 (OK=77918  KO=28029 )
> min response time                                      0 (OK=18     KO=0     )
> max response time                                  12017 (OK=12017  KO=5706  )
> mean response time                                   601 (OK=817    KO=1     )
> std deviation                                        869 (OK=921    KO=92    )
> response time 50th percentile                        215 (OK=534    KO=0     )
> response time 75th percentile                        921 (OK=1202   KO=0     )
> mean requests/sec                                2779.375 (OK=2044.073 KO=735.303)
```

**Comment by aidylewis** [comment]
Thanks for your replies. I have spoken to someone from AWS. He doesn't think an HVM image will help as we are running a relatively low load of 600 r/s. We are also well within our bandwith usage for a c3.2xlarge. CPU seems to be concentrated on one core and doesn't go above 25%. We think that something is shutting down the connections when we hit a certain rate. It may be our VPN, as @pdalpra has achieved a mean of 2779 r/s. I am going to try from Google cloud.

**Comment by aidylewis** [comment]
This is not a Gatling issue, but an infrastructure issue. As @pdalpra has mentioned we can reach 2000+ r/s on a private cloud. My belief is that our VPN is limiting request rate. Many thanks for your replies and @ceeaspb's informative post.

**Comment by slandelle** [comment]
Hi Aidy,

That's good news, at least from our point of view ;-)

Where do you have VPN involved? When we tested, we directly hit the system that was configured in the simulation. Do you hit a different one?

**Comment by aidylewis** [comment]
We use an Amazon VPC/VPN and something is limiting the rate, somewhere. But as yet, I don't know what.

**Comment by slandelle** [comment]
The best solution is to ask to your AWS support.

There was a time where you had to fill a special form when you wanted to use an EC2 instance for sending tons of requests. Otherwise they would think the instance was used for DDoS and shut it down. Maybe there's still this kind of protection going on.

**Comment by aidylewis** [comment]
The NATs are getting maxed out. The options are: increase the size of the NATs or run the tests from a public subnet.
