### ISSUE TITLE
SBT Plugin: it:test does not run Gatling simulations

### ISSUE THREAD

**Issue by yanns** [gatling/gatling#2763]
instead of using `it:test`, one should use `gatling-it:test`

**Comment by slandelle** [comment]
Assigning to our world renowned sbt expert.

**Comment by pdalpra** [comment]
Indeed, it seems that if `test` triggers `gatling:test`, `it:test` does not trigger `gatling-it:test`.
Will investigate.

**Comment by pdalpra** [comment]
@yanns Fixed, as it was more a bug in the plugin than an error in the documentation ;)

**Comment by yanns** [comment]
@pdalpra great!!! :+1:

**Comment by slandelle** [comment]
@pdalpra What was #2816 intention exactly?

Now, `test` and `testOnly` no longer discover and run Gatling simulations. You have to explicitly call `gatling:test` or `gatling:testOnly`.

If this was intentional, this is quite a breaking change that has to be properly considered, and if accepted, documented.

**Comment by pdalpra** [comment]
Well, it's that or you have to explicitly use test:test to run Scalatest/Specs2, which is more annoying.
Using the galling prefix was the intended way to use it, the fact that the other way worked was, in the end, a bug.
BTW, the documentation uses the prefixed versions.

**Comment by pdalpra** [comment]
Short way to say it : this was a bug, not a feature :)

**Comment by pdalpra** [comment]
I was sure that I mentioned that to you back then...

**Comment by slandelle** [comment]
> Using the galling prefix was the intended way to use it, the fact that the other way worked was, in the end, a bug.

My understanding has always been that we could run with `test` and `testOnly`.
A bug is in the implementation.
My understanding is that it was a mistake in the plugin design, that causes us to conflict with other tests.
Hence a behavior change is necessary, and has to be advertised in 2.2.

> BTW, the documentation uses the prefixed versions.

Really? Where?
Not in the latest [published doc](http://gatling.io/docs/2.1.7/extensions/sbt_plugin.html#usage) nor in [master](https://github.com/gatling/gatling/blob/master/src/sphinx/extensions/sbt_plugin.rst#usage).

> I was sure that I mentioned that to you back then

I really don't remember, but well: lack of sleep + buffer overflow... ;-)

Don't get me wrong: I'm perfectly fine with this change, as it seems the only way to not conflict with unit tests and it should have been the proper behavior in the first place. Just that we have to properly advertise it for 2.2.0.

**Comment by pdalpra** [comment]
Sure, I'll rework the documentation when I get back from Punta Cana, if it can wait.

**Comment by slandelle** [comment]
>  when I get back from Punta Cana

Poseur! Yeah, let's do that when I come back from NYC! Take that!

**Comment by aidylewis** [comment]
@pdalpra Do you want me to update the docs. Adding the prefix and a brief explanation about unit test conflict?

**Comment by Seetaramayya** [comment]
`gatling:testOnly computerdatabase.BasicSimulation` is not triggering simulation if I keep sources in different directory, but simulations are working fine if sources are in `src/test/scala`. 

I kept sources in `src/test/perf`and instructed gatling to pick from there. Here is [my build.sbt](https://github.com/Seetaramayya/gatling-sbt-plugin-demo/blob/experiment/build.sbt) 

is it expected behavior or is it bug?

**Comment by michaelahlers** [comment]
@Seetaramayya, I've encountered that problem as well (see #3301).
