### ISSUE TITLE
HTTP: Connection pool is broken when using a proxy

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2795]
Only 2.1 is broken, master is fine.

**Comment by sebdotv** [comment]
fixes `java.lang.ClassCastException: com.ning.http.client.ConnectionPoolPartitioning$ProxyPartitionKey cannot be cast to java.lang.String` reported at https://groups.google.com/forum/#!topic/gatling/_TK0DXCUAgA

**Comment by gChurchel** [comment]
I just downloaded from gatling.io this afternoon and am getting this error consistently when trying to run the simulations from behind a proxy server. Had to add a .prox(Proxy... line to the URL stuff to get any connection but then this error comes up every time.

**Comment by slandelle** [comment]
@gChurchel Which version did you download exactly?

**Comment by slandelle** [comment]
Ah OK. You can see that bug is marked as fixed for 2.1.8 which hasn't been released yet.

**Comment by skytraveler** [comment]
waiting for release 2.1.8:)

**Comment by M3lkior** [comment]
+1 

There is a previous version to use to avoid this exception ?

**Comment by slandelle** [comment]
> waiting for release 2.1.8:)

Best way to get releases is to contract for support :)

**Comment by sebdotv** [comment]
This is probably not the place to discuss the matter, but anyway: I understand your need to start making money, but I don't think you should try making it on a blocking bug of the 2.1.x branch. I've been forced to use 2.1.6 and its broken sbt plugin for 4 months now... But it's your business and prerogative of course.

**Comment by slandelle** [comment]
It's a matter of priority: we work like crazy, our time/resources is limited, and it's expected that we give priority to our customers, and taking some time to release 2.1.8 has a lower priority than doing our best to make 2.2.0 land in March. 
Then, this issue is minor IMHO: running Gatling through a proxy is not a very common use case and probably not a production one, but a dev one.
Finally, the fix is there, you can grab the code.

Feel free to get in touch if you want to discuss privately.

**Comment by sebdotv** [comment]
Thanks Stephane for clarifying this. You're right, it's a dev issue in my case (which makes using 2.1.6 broken sbt plugin painful).

**Comment by pdalpra** [comment]
As there were no breaking changes related to the SBT plugin interaction
with Gatling between between its 2.1.6 and 2.1.7 release, you should be
able to use gatling-sbt 2.1.7 with Gatling 2.1.6.

Cheers,

Pierre

**Comment by robertgates55** [comment]
This is currently a blocker on some production testing I'm doing [bit of a niche use case], and I wondered what my options were. Obviously I understand that everyone's very busy, and I'm not expecting any magic given that I don't pay for support - just couldn't quite work it out from the above.

 - 2.1.8 resolves it - is there any indication yet (eg days or months?) when this might be being released?
 - 2.2.0 snapshot would presumably resolve it. I've tried this and got lots of compilation errors, presumably because there'll be some sort of migration required. I couldn't work out from the 2.2.0 migration ticket what I'd need to update to fix though, so have rolled back to 2.1.7 for now
 - would 2.1.6 fix it? Or is that a different, sbt plugin specific, issue entirely?

Any help much appreciated, otherwise I'll await 2.1.8 patiently!

**Comment by slandelle** [comment]
@robertgates55 There won't be a public 2.1.8. We plan on releasing 2.2.0 at the end of the month. If the public releases are not fast enough for your needs, consider subscribing to our support offer.

**Comment by robertgates55** [comment]
@slandelle No that's great - we look forward to it - Thanks.
