### ISSUE TITLE
Gatling 2.2.0 simulation.log format lacks important timing stats

### ISSUE THREAD

**Issue by dmand** [gatling/gatling#2992]
Hi.

It looks like since 2.2.0 Gatling dropped some fields from simulation.log file, namely `requestStartDate`, `requestEndDate`, `responseStartDate` and `responseEndDate`. You can compare [old](https://github.com/gatling/gatling/blob/5ec2005aa05aa72d6a1a2234eb55f5d90576e616/gatling-core/src/main/scala/io/gatling/core/result/writer/FileDataWriter.scala#L76) and [new](https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/stats/writer/LogFileDataWriter.scala#L95) log formats. These stats were useful for us because it was possible to calculate connection time and latency metrics from them.

Was this removal intentional? Is there any way we can have these stats back? Is there a way to extract these metrics from somewhere else?

**Comment by slandelle** [comment]
Yes, this removal was intentional. We only used those timestamps for computing latency, meant as the duration between last byte sent and first byte received. IIRC, this concept came from JMeter plugins, but it didn't make sense for most users for whom latency and response time are the same thing.

We've always warned that the log file format was not a public API and it was only an internal support for producing our reports. It seems that you were parsing it on your own and have built your own reporting system, which is not a supported usage.

TCP connect duration metric is available in FrontLine, our commercial product, along with other metrics such as bandwidth, TLS handshake, DNS resolution, etc. We might also introduce TTFB (time to first byte, which is the difference between first byte sent and first byte received) which is a more standard metric.

Our policy is that all new metrics will only go in FrontLine.
