### ISSUE TITLE
Core: Have expression resolution convert Java collections to Scala ones

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3053]
Eg, it would be nice if `io.gatling.commons.util.LowPriorityTypeCaster` could automatically convert/warp:
- `java.util.Map` to `scala.Map`
- `java.util.Collection` to `scala.Seq`
- `java.util.Set` to `scala.Set`

**Comment by PixelSpirit** [comment]
Hi !
Scala Standard API proposes a way to convert implicitly Java Collections types into Scala ones.
Theses wrappers are available in the ```collection.JavaConverters._``` class and globaly proposes bidirectional convertion for thoses types : 
- ```Iterator```                           <=> ```java.util.Iterator```
- ```Iterator```                           <=> ```java.util.Enumeration```
- ```Iterator```                           <=> ```java.util.Iterable```
- ```Iterator```                           <=> ```java.util.Collection```
- ```mutable.Buffer```               <=> ```java.util.List```
- ```mutable.Set```                   <=> ```java.util.Set```
- ```mutable.Map```                 <=> ```java.util.Map```
- ```mutable.ConcurrentMap```<=> ```java.util.concurrent.ConcurrentMap```

You can have more informations [here](http://docs.scala-lang.org/overviews/collections/conversions-between-java-and-scala-collections.html).

Since Scala already provides these functionnalities, do you really need to add it to the ```io.gatling.commons.util.LowPriorityTypeCaster```class ?

**Comment by slandelle** [comment]
> You can have more informations here.

No real need to provide Scala beginner pointers here... ;-)

Both `JavaConverters._` and `JavaConversions._` are *implicit* conversions, ie triggered by the compiler that adds some conversions in the emitted bytecode.
`LowPriorityTypeCaster#genericTypeCaster` works at *runtime* and checks expected class `isAssignableFrom` actual one.

**Comment by slandelle** [comment]
Typical usage here is fetching some JSON array (not the sequence of JSON array children) with some `jsonPath` check, hence getting a `java.util.ArrayList` and trying to loop with a `repeat` that expects a Scala `Seq`.

**Comment by slandelle** [comment]
Related to #3195

**Comment by slandelle** [comment]
Superseded by #3195
