### ISSUE TITLE
Version 2.2 (and possibly 2.1) introduced a new limitation on lower value of ramp seconds

### ISSUE THREAD

**Issue by BCkwilliams** [gatling/gatling#3065]
With 2.0.3, a script that said xxxxxScenario.inject(rampUsers(1) over (0 seconds)) - worked, and started all users with no ramp up 
With 2.2.x, the same script will leave all simulations with the ramp of 0 in a waiting state

Proof - edit the user-files/simulations/computerdatabase/advanced/AdvancedSimulationStep05.scala to contain (0 seconds) and run that simulation - you will hang for a VERY long time

0 second ramp up should still be 0 seconds

I'm changing my default to 1 second until a fix is available

**Comment by BCkwilliams** [comment]
actually I've also tried changing AdvancedSimulationStep05.scala with
val myRamp = java.lang.Long.getLong("ramp", 0L)
and
(myRamp seconds)

But - same result

**Comment by slandelle** [comment]
The behavior you describe wasn't intended and isn't supported.
A 0 ramp duration should result in a division by 0 and an infinite injected value at the first instant.
If you want to inject users at once, use the proper intended step.

What we're going to do it add some controls so that passing a 0 duration is explicitly forbidden with a proper Exception.

**Comment by slandelle** [comment]
OK, I guess it should be fine to support this.
