### ISSUE TITLE
Jenkins: charts are broken due to lack of security 

### ISSUE THREAD

**Issue by vmurin** [gatling/gatling#3075]
To comply the security requirements **no inline java-script**  should be used  on the gatling report pages.
The solution mentioned in Jenkins-Wiki (to disable security policy - ' unsafe-inline') is not acceptable in most cases.

Suggested solution:
- the dynamically generated javascripts  should be saved and included as an external script.  
Although it does not provide full security (via hash or nonce) it allows to exclude most unsafe "inline script" case.

Related Links:
- https://wiki.jenkins-ci.org/display/JENKINS/Gatling+Plugin
- https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy#ConfiguringContentSecurityPolicy-DisableCSPforallPlugins
- https://www.w3.org/TR/CSP2/#script-src-hash-usage
- [Document needed Content-Security-Policy Settings for Gatling Reports](https://issues.jenkins-ci.org/browse/JENKINS-32038?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27gatling-plugin%27)

**Comment by slandelle** [comment]
AFAIK, the Jenkins team introduced this breaking change, without providing a proper workaround, just in case your Jenkins servers are not properly secured and someone might be injecting malicious code in those static files. If that's the case, I sincerely disagree with this decision, and properly securing servers would have been the right thing to do.
Also, this "security" configuration can only be disabled globally. Why not per plugin???
IMHO, this is a Jenkins issue, and it's up to the Jenkins project to provide a proper solution.

Those scripts are generated as external files because they are shared with all the reports pages. I don't think we'll ever go to the length of customizing the way the reports are generated just to cope with Jenkins.

FWIW, we don't have such limitation with the FrontLine Jenkins plugin as FrontLine has it's own server and APIs, so we can depend as less as possible on Jenkins features and architecture choices.

**Comment by slandelle** [comment]
I'll close this as "Won't fix" for now. We'll reconsider if some solution shows up that don't require us a huge effort to adapt.
