### ISSUE TITLE
JMS: Use async MessageListener instead of blocking receive

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3137]
I have no idea why we use listener threads that call blocking `receive` instead of directly creating multiple `replyConsumer`s from the main thread, and have all of them use `MessageListener`s.

Maybe @jasonk000 has a clue, as he's the one who originally contributed this?

@thkluge @mgurov @pwielgolaski Thoughts?

**Comment by jasonk000** [comment]
This goes a long way back, but from memory ..

The primary reason is that most if not all JMS implementations, when using an async MessageListener, actually create a thread to do the MessageListener-ing for you anyway, so you don't win anything apart from some complexity. For those that don't, the MessageListener thread is already processing an event, so the next message in queue will not be picked up until after the listener is complete which skews the timings.

This may no longer be the case or there may be a better way to handle it as I haven't worked on JMS for quite some time. Particularly since JMS2.0 specs have been released some of the implementation drivers may be a bit smarter about this.

**Comment by slandelle** [comment]
@jasonk000 Thanks a lot, Jason!

Well, I guess we'll have to dig in modern implementations and check how they behave. Using a MessageListener would actually make things more simple for us. Also, I don't think we'd harm performance as we directly send the message to the actor.

Stay tuned :)
