### ISSUE TITLE
Maven plugin : logback ignored

### ISSUE THREAD

**Issue by kemuning** [gatling/gatling#3210]
It seems to me that when invoking gatlin via maven, i.e.:
`mvn clean gatling:execute`
the logback.xml is purely & simply ignored. Just try by changing logback.xml into a not well form XML structure, nothing happen.

**Comment by slandelle** [comment]
Sorry, I can't reproduce.
I cloned our [demo](https://github.com/gatling/gatling-maven-plugin-demo), renames `logback-test.xml` into `logback.xml`. Changing logging level to DEBUG or INFO does work.

Closing for now, as I suspect the problem is on your side.
Please feel free to provide a reproducer and I'll reopen.

**Comment by kemuning** [comment]
True, just cloned downloaded the demo. Thanks.
