### ISSUE TITLE
SBT plugin: Using custom source roots causes ClassNotFoundExceptions

### ISSUE THREAD

**Issue by michaelahlers** [gatling/gatling#3301]
Changing the source root breaks `gatling:test` and `gatling-it:test` commands.

For example, a setting such as (documented by [_SBT plugin: Default settings_](http://gatling.io/docs/current/extensions/sbt_plugin/#default-settings)):

```scala
scalaSource in Gatling := sourceDirectory.value / "gatling" / "scala"
```

Will cause `gatling:test` to fail with:

```
[error] Uncaught exception when running computerdatabase.BasicSimulation: java.lang.ClassNotFoundException: computerdatabase.BasicSimulation
[trace] Stack trace suppressed: run last gatling:test for the full output.
[info] Simulation(s) execution ended.
[error] Error during tests:
[error] 	computerdatabase.BasicSimulation
[error] (gatling:test) sbt.TestsFailedException: Tests unsuccessful
```

Everything works as expected with the `scalaSource in Gatling` left unchanged and simulation sources in `src/test/scala`.

Using Scala 2.11.4 (a different—but seemingly unrelated error—occurs with Scala 2.12), gatling-sbt 2.2.1, and gatling-test-framework 2.2.5.

**Comment by slandelle** [comment]
I'm sorry, but I don't expect any Gatling core committers will have time to investigate this, as the plugin works perfectly fine with the standard configuration. I'm flagging this one as "Contributions welcome".

If you think that's a Gatling issue, feel free to contribute.

If that's a general sbt usage question, maybe the sbt mailing would be more suited.

**Comment by michaelahlers** [comment]
@slandelle, granted, but it's worth noting the [plugin's official documentation advertises this setting as configurable](http://gatling.io/docs/current/extensions/sbt_plugin/#default-settings).

**Comment by slandelle** [comment]
I had a look, and behavior is super weird.

I tries changing `sourceDirectory in Gatling := baseDirectory.value / "src" / "gatling"` (sbt 0.13.16).
Then, generated class files suddenly end up in `target/gatling-classes` instead of `target/test-classes`.
Resources files are still copied in `target/test-classes`.
And test framework keeps on having `target/gatling-classes` in its classpath, hence the ClassNotFoundException.

I'm pretty sure changing `sourceDirectory` used to work, but I have no idea when it stopped, and if it's a bug on our side or in sbt. And we no longer have a sbt roxxor with us.
If it's an sbt bug, I'm afraid we'll have to first upgrade our tooling to sbt 1.0, which we can't do yet, see #3351.

It would be great if some community member with sbt skills could chime in. Maybe @xuwei-k?

**Comment by slandelle** [comment]
@pdalpra Has you seem to still be alive, assuming your sbt ninja arts are not too rusty, do you have a clue about this one?

**Comment by pdalpra** [comment]
I'll have a look ;)

**Comment by slandelle** [comment]
Would be super awesome!!!

**Comment by HugoTigre** [comment]
I had the same problem and this worked:

`lazy val GatlingTest = config("gatling") extend (Test)`
`scalaSource in GatlingTest := baseDirectory.value / "test-gatling"`
`lazy val root = (project in file(".")).enablePlugins(GatlingPlugin).configs(GatlingTest).settings(inConfig(GatlingTest)(Defaults.testSettings): _*)`

Setting configs and settings should fix the problem. ("test-gatling") is where i have the simulations and feeders.

**Comment by slandelle** [comment]
@HugoTigre Thanks for your help!
Actually, it seems this is enough:

```scala
scalaSource in Gatling := sourceDirectory.value / "gatling" / "scala"
lazy val root = (project in file(".")).settings(inConfig(Gatling)(Defaults.testSettings): _*)
```
