### ISSUE TITLE
HTTP: Allow passing generated http headers map on each request

### ISSUE THREAD

**Issue by alexeyknyshev** [gatling/gatling#3347]
Currently signature is:
`headers(newHeaders: Map[String, String])`

But it would be great to have an opportunity passing generator instead of constant Map like it's done for
`header(name: String, value: Expression[String])`
but for bunch of header : value pairs

Thanks

**Comment by slandelle** [comment]
IIRC, we can't have `headers(newHeaders: Map[String, Expression[String]])` because the implicit conversion from String to Expression[String] (eg for EL resolution) wouldn't be resolved and code like `headers(Map("foo" -> "${bar}", "baz" -> "${qix}"))` would no longer compiler.
That's the reason why the currenlty have `headers(newHeaders: Map[String, String])` and trigger the values EL solution manually.

Maybe having `headers(newHeaders: Expression[Map[String, String]])` would be possible, but the impact on our code is not trivial.

Feel free to give it a try, contributions welcome :)

**Comment by slandelle** [comment]
Closing for now, impact is really huge and benefits don't seem that great.

**Comment by motinis** [comment]
Why not implement headers(session => Map[String, String])? This would be consistent for example with things like StringBody, and would give the necessary flexibility without compromising existing code.

**Comment by slandelle** [comment]
@motinis Because:
1. it would require major changes in current implementation where we store internally in `Map[String, Expression[String]]`
2. it would break existing `headers(Map[String, String])` that let you write `headers(Map("foo" -> "${foo}"))`

**Comment by motinis** [comment]
@slandelle thanks for your response - my apologies for not being familiar. Would `session => Map[String, Expression[String]]` be feasible? Basically the goal here is to be able to have dynamic header names.

**Comment by slandelle** [comment]
That's the whole point: header names can currently only be static, only values can be dynamic.
When I designed this, I didn't expect dynamic header names to be a valid use case, and frankly, you're the first one to every ask. Why do you need this exactly?

**Comment by motinis** [comment]
It simplifies setup - we could then reuse the exact same simulation and maintain control via files, or programatically. Sometimes there can be additional headers / steps to be done, depending on the environment we're running in. It can be done inside the simulation, it just means we start violating DRY since we have to update simulation code additionally to e.g., existing test code.

**Comment by valinad** [comment]
Did the situation change? I also need dynamic headers keys (and values) using jdbs feeders (headers stored in db). With current method headers(Map) I can not get header key from session

**Comment by slandelle** [comment]
No. Ticket has never been reopened. Contributions welcome.

**Comment by zckoh** [comment]
Is this still not supported? We also have a use case where we would need to have the header key dynamic and the number of headers are not static.
