### ISSUE TITLE
AsyncHttpClient using DefaultChannelId directly

### ISSUE THREAD

**Issue by jdreyesp** [gatling/gatling#3369]
gatling-http module dependency: asynchttpclient , has a netty class 'DefaultChannelId' directly copied into their library!

This should not be there, as this library should need to use netty as a dependency. I've seen that latest alpha versions of this library: org.asynchttpclient:async-http-client:2.1.0-alphaXX don't have this netty class copied into their src.

Thanks!

**Comment by slandelle** [comment]
AHC 2.0 has a backport of Netty's `DefaultChannelId` because it needs it for the DNC codec backport. This isn't supposed to conflict with Netty as `DefaultChannelId` only exists in Netty 4.1 and AHC 2.0 and Gatling 2 target Netty 4.0.

AHC 2.1 and Gatling 3 will target Netty 4.1 and the `DefaultChannelId` has of course been removed.
