### ISSUE TITLE
Update to netty 4.1

### ISSUE THREAD

**Issue by politrons** [gatling/gatling#3378]
Maybe this has been asked thousand of times. But any estimation when you will release a version with support for netty 4.1?.

Regards

**Comment by slandelle** [comment]
Indeed, you can find the answer on our mailing list: when we'll release Gatling 3, hence when we'll have implemented HTTP/2 support and finished revamping WebSocket support, most likely end of Q1 2018. Then:
* master already uses Netty 4.1, you can fetch from Sonatype
* FrontLine already uses Netty 4.1
* you can isolate Gatling tests in their own module instead of clashing with your application's classpath

One more thing: please use the mailing list for questions, the bug tracker is for bugs
