### ISSUE TITLE
Core: Replace Jackson CSV parser with SimpleFlatMapper + drop escape

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3383]
SimpleFlatMapper provide a CSV that's usually more efficient than the Jackson's one.
So far, Jackson still beats SimpleFlatMapper on ver large file with one single unquoted column.

Moreover, SimpleFlatMapper can return simple arrays while Jackson always return Java Maps.
This let us directly map to a structure that's optimized for our usage (adding to the Session's Map) and save lots of intermediate objects allocation.

Let's also drop escape and stick to RFC4180 that specifies double quote a escape character.

**Comment by slandelle** [comment]
Thanks @arnaudroger for your help and this cool library!

**Comment by arnaudroger** [comment]
@slandelle just would like to clarify something, the disableUnescaping in sfm actually will pass through the string as it was originally in the csv 
i.e. with disableUnescaping for a quoted string `"\"hello\""` you would get `"\"hello\""` in the callback otherwise you would get `"hello"`. It's mainly used if you know your csv does not contain field are you want to do the post processing yourself.
The unescaping in sfm is pretty optimized.
- if not quoted it's straight through
- if no escaped char in the string then it just callback with the start index and end index shifted to exclude the quote.
- if there was escaped char the unescaping is done in place in the char buffer with no allocation.

just wanted to make that clear.

**Comment by slandelle** [comment]
Yep, I don't know why it was there in my initial version, but that was a mistake and it was removed from both benchmark and Gatling [commit](https://github.com/gatling/gatling/commit/5b9823a19d353e01447663e3ee91ded75c3b150d#diff-f07f6d9b02e6205945069ef966c06739R42).

Thanks for pinging :)

**Comment by slandelle** [comment]
@arnaudroger I've properly aligned Jackson and sfm code (both return String arrays) in my benchmark and have [updated results](https://github.com/slandelle/csv-parser-benchmark#results).
Jackson still wins on cookies... #ShamelessTaunt :)

**Comment by arnaudroger** [comment]
not really surprised it does :) hard to be optimised for all the cases :)
