### ISSUE TITLE
missing 2.3.0 tag on GitHub

### ISSUE THREAD

**Issue by xuwei-k** [gatling/gatling#3420]
- https://repo1.maven.org/maven2/io/gatling/gatling-core
- https://github.com/gatling/gatling/releases

<img width="608" alt="2018-02-09 15 14 00" src="https://user-images.githubusercontent.com/389787/36014198-e49bf050-0dab-11e8-99e9-b9952dcc4ae1.png">
<img width="511" alt="2018-02-09 15 13 33" src="https://user-images.githubusercontent.com/389787/36014199-e4bec5da-0dab-11e8-88a1-96fa88cc4758.png">

**Comment by slandelle** [comment]
Hi @xuwei-k 

For some reason (our private/enterprise version build), we couldn't manage to keep on using the sbt-release plugin that was creating tags automatically. I'm not saying it wouldn't have been possible, just that we no longer have an sbt expert amongst us.

Generally speaking, we really don't care about those tags: we don't use them, AFAIK they're only helpful for unfriendly forks maintainers and the way Github automatically translates git tags into so-called "releases" in non sense and something I wish we could disable.

In the end, providing git tags is for us a way less pressing matter than being able to provide proper snapshots on Sonatype, which is no longer possible since we migrated to sbt 1, see #3406 :(

If sbt keeps on getting in the way, I guess we'll move to something else at some point, maybe gradle.

Cheers
