### ISSUE TITLE
Gatling 3 JMS performance  with IBM MQ8

### ISSUE THREAD

**Issue by LukasHavemann** [gatling/gatling#3445]
Hello,

we used the latest gatling 2 release for jms loadtesting with 8000 req/sec against IBM MQ 8 and had no problems. With gatling 3 we have big performance issues with just 4000 req/sec. 

To verify that gatling is the cause, we setup our gatling 2 & 3 loadtestdriver on one machine, a teststub on a second machine and IBM MQ 8 on a thrid machine. We ran the same scenario with gatling 2 and gatling 3 multiple times. Here are the two reports with the same machines, same teststub and same scenarios. 

Best Regards
Lukas

Gatling 2
![gatling2](https://user-images.githubusercontent.com/655563/37845054-caefef46-2ec9-11e8-93f4-023928c6b4af.PNG)

Gatling 3
![gatling3_performance](https://user-images.githubusercontent.com/655563/37845060-cf2f547a-2ec9-11e8-83f2-aa66e2fca25f.PNG)

**Comment by slandelle** [comment]
We don't see such performance regression on our internal benchmarks, where we test Artemis.

Results below where produced on my laptop (I would expect way better results on our Linux boxes):
<img width="900" alt="artemis" src="https://user-images.githubusercontent.com/849197/37864354-b564418c-2f6d-11e8-9615-fba04b04ae55.png">

Several possibilities:

* The main difference between Gatling 2 and Gatling 3 JMS support is that we now use `javax.jms.MessageListener` instead of  blocking`javax.jms.MessageConsumer#receive`. If that's the issue with MQ, I advice you get in touch with your IBM support to get this fixed.
* The problem is with your platform and is not related with Gatling
* The problem is indeed with Gatling

If you want us to investigate the latter, please provide a complete standalone application that reproduces your issue and we can run on our side (hence not based on IBM MQ that we obviously don't have licence for).

**Comment by LukasHavemann** [comment]
We do not see this behavior with low req/sec rates. With 1500 req/sec Gatling 3.0 performs nearly as good as Gatling 2.0.

According to MQExplorer it seems that there is only one consumer that receives the messages. So it seems that the IBM mQ provider starts only one receiver thread. This corresponds with the behavior we experienced in our own application. We measured that one session + one receiver thread was capable of receiving ~2400 messages per sec not more. It seems that IBM MQ needs multiple paralell sessions in order  to surpass the 2400 message treshhold. This was possible with Gatling 2.0, since the number of paralell consumers was configurable.

Since Gatling 3.0 allows only a single receiver thread, all JMS implementions which rely on multiple sessions for maximum performance, should have a problem. This behaviour of MQ8 is obviouly not great, but as far as we know the JMS Speicification does not require a single session to bring 100% of the thoughput. We think our problem would be resolved if Gatling 3.0 would allow multiple receiver threads to be configured.

Due to licensing and intellectual property reasons, we are not able to provide a complete standalone application. If you want to test against ibm mq yourself, there is a docker image on DockerHub https://hub.docker.com/r/ibmcom/mq/

**Comment by slandelle** [comment]
IBM sure knows how to milk crappy code...

> Due to licensing and intellectual property reasons, we are not able to provide a complete standalone application. If you want to test against ibm mq yourself, there is a docker image on DockerHub https://hub.docker.com/r/ibmcom/mq/

Thanks, but we really don't have time to investigate enterprisey softwares such as IBM MQ without a contract.

If you're interested, please contribute a way to restore [Gatling 2 behavior with multiple consumers running in dedicated threads](https://github.com/gatling/gatling/blob/2.3/gatling-jms/src/main/scala/io/gatling/jms/action/JmsReqReply.scala#L67-L105). Just make sure that current behavior is the default.
