### ISSUE TITLE
Provide access to Session in transformResponse

### ISSUE THREAD

**Issue by asaarilahti** [gatling/gatling#3461]
Background:
We are testing a service which also calls other services. We would like to subtract the response times of these dependent services from the total response time Gatling sees. This would allow to test the service in somewhat isolated fashion, where slowdowns of dependent services would not be accounted to the service under test.

We can currently adjust the response end time by using transformResponse. However, to do the adjustment we would need to access data from the session. To my understanding that is not possible currently.

I'd be happy to provide a PR, if a change to include the session would be welcome. I have currently a draft version, which just changes PartialFunction[Response, Response] to Function2[Response, Session, Response]. However, that won't be backwards compatible and will lose the benefits of a partial function. Couple of question related to that:
- Should the change be kept backwards compatible with 2.3 (this would target 3.0)?
- Does the proposed solution to use Function2 look ok, or would some other approach like a Trait be preferable?

**Comment by slandelle** [comment]
> Should the change be kept backwards compatible with 2.3 (this would target 3.0)?

Definitively impossible in 2.3. And I don't think there will be a new release on this branch anyway.

> Does the proposed solution to use Function2 look ok, or would some other approach like a Trait be preferable?

> However, to do the adjustment we would need to access data from the session.

Why is that so? You'll be passing the dependent services time in the same response, but you won't be able to grab them from checks as transformer is applied **before the checks**. And there's no way to change that, as transformers are mainly intended for deserializing binary payloads such as protobuf.

I advice you pass this time as an HTTP header (typically [Server-Timing](https://w3c.github.io/server-timing/)) instead of inside a JSON payload so it's easy to grab directly from Response without any complex parsing.

**Comment by asaarilahti** [comment]
> You'll be passing the dependent services time in the same response

Seems I didn't mention a key point - in our case the data to the session is already provided by a feeder, so it's not coming from the response. We are replaying traffic from production so we know the expected dependent service response time for every request in advance (and the mock services will respond honoring on that, with minor variances in practice).

It sounds that our use case might be quite unconventional, so not sure if the change would be generally useful. What do you think?

**Comment by asaarilahti** [comment]
At the end I think the use case is too special to warrant the change - closing.

**Comment by slandelle** [comment]
Agree :)
