### ISSUE TITLE
Test summary logged using println

### ISSUE THREAD

**Issue by adamdougal** [gatling/gatling#3571]
At the moment the test summary is logged using println https://github.com/gatling/gatling/blob/11308fcf5b2048f0a28a585529d13b5c0337d85f/gatling-core/src/main/scala/io/gatling/core/stats/writer/ConsoleDataWriter.scala#L75

This causes issues when shipping logs to Kibana in a logstash encoded format using the logstash-logback-encoder as println does not use that encoder. Is this done intentionally?

I did originally raise this issue here https://groups.google.com/forum/#!topic/gatling/Kq-hDp3oFkk but got no response. 

If it's ok to change this to use a logger I'm happy to contribute.

**Comment by slandelle** [comment]
Sorry, but all new features regarding stats (additional stats, pushing stats elsewhere) fall into the scope of [FrontLine](https://gatling.io/frontline), our Enterprise version.

For example, FrontLine provides a public API you can use to extract the stats, and a Grafana datasource.

**Comment by adamdougal** [comment]
I think this is more about logging rather then stats. At the moment we can't even turn these logs off if we don't want them. This is a problem with the open source tool.

**Comment by slandelle** [comment]
> At the moment we can't even turn these logs off if we don't want them.

Yes you can, remove `console` from the `writers` in `gatling.conf`.

**Comment by adamdougal** [comment]
Ok, that's my mistake. Though I'm still not sure why this would use a `println` rather then a logger that you can have more control over.

**Comment by adamdougal** [comment]
Would you be open to have a new implementation of `DataWriter` that used a logger instead?

**Comment by slandelle** [comment]
No, for the very same reason: we need to make a living.

> Sorry, but all new features regarding stats (additional stats, pushing stats elsewhere) fall into the scope of FrontLine, our Enterprise version.

I'll sound pushy, but I think it would be fair that [billion dollars companies](https://www.statista.com/statistics/273693/bskybs-annual-revenue/) that have been using an open source software for years would consider helping the company behind the technology.

**Comment by adamdougal** [comment]
Ok, I'll concede on this. Though I think it's unrealistic to expect someone/a company to pay money for a tool that works perfectly fine for them, just to have finer grain control over their logs. We're not asking for real time live graphs or monitoring of injectors. This is something we are more then happy to do the work for to improve the tool, so it's shame we can't contribute in that way.

**Comment by balooo** [comment]
@slandelle I also think you have quite a harsh approach in my opinion.  If you goal is to make a living, it might be good to not be so aggressive to potential customers, but  oh well :man_shrugging:

**Comment by slandelle** [comment]
Sorry if I sounded harsh, that wasn't my intent.

We've drawn a clear line between what goes in Gatling OSS and what goes in Gatling FrontLine:
all new things related to stats/exports/integrations go into Gatling FrontLine.

We're more than happy with contributions related to core Gatling features such as HTTP and users orchestration. But we can't make any exception to the above rule.

**Comment by balooo** [comment]
@slandelle I am sorry but I don't really understand your reasoning, although I understand your concern around protecting the Enterprise value.

 Just to confirm, your strategy is to prefer for us to fork this project so that we can use a logger for a single line of code where you are currently using println, pushing us further away from wanting the Enterprise solution because you are classifying using a logger to output the summary as part of `stats/exports/integrations`, although that information is already being outputted in a different form?  

To be honest, this entire thread so far makes me far less inclined to introduce a dependency on the enterprise project.  I believe gatling is great as a project, I believe you should get paid to support and continue working on it full time, I also believe large companies should pay and help support opensource initiatives.   The problem is that I also believe your approach will alienate many people, or at least me and all the people I talk to about this.  It's a very simple code change, that actually makes it more consistent, as the majority of of your code base uses loggers (as any developer would expect). 

You are not even arguing about not outputting that data because it's `stats/enterprise` data.  The data is there and available in the logs already!  The only difference is the primitive output mechanism.  The fact that many modern log shipping frameworks expect json/structured logs means that using println automatically makes you a less attractive product for both enterprise and non enterprise adopters.  These println statements just create noise in most modern log shipping frameworks I have worked with as they cannot be interpreted as a single event.  This is genuine feedback.

I would urge you to reconsider the quick decision, because I believe this suggestion exposes no more information than you currently do, moves you towards a more standardized output like the rest of your code base, and would actually show you positively engaging in improving your entire product offering, OSS and Enterprise. 

The functionality you are planning as part of Enterprise are still attractive to companies like ours, e.g. aggregation of metrics etc, grafana datasources etc.  I think you've convinced yourself that any improvements to OSS is a risk to Enterprise.  Just doesn't sit well with me.

**Comment by slandelle** [comment]
@balooo Thank you for sharing your concerns. We don’t see improvements of the OSS as a risk, quite the contrary: you can have a look at all the work that’s been put into upcoming Gatling 3 OSS.

Our Enterprise version, Gatling FrontLine, aims to provide our users with advanced features in terms of metrics, integration and automation. This Enterprise version was designed by the feedback of our users who built their own integrations with Gatling but then struggled to stabilize them and maintain them over time.

We believe this Enterprise version is a win-win for everyone: we make you save time and money, we guarantee you stability and, at the same time, you help the open-source project continue to develop.

We would be more than happy to continue this discussion live and convince you that we are still committed to improve load testing, both for our OSS users and for our enterprise customers.

Anyway, thank you for using Gatling

**Comment by balooo** [comment]
@slandelle Thanks for the reply, but I still don't think you actually addressed the points I was trying to raise regarding this particular issue.  I still don't understand how the suggested change is against your commercial strategy.  The points I was trying to articulate are that this request:

- doesn't expose any data that would previously be inaccessible / enterprise.
- doesn't suggest structuring the results in a way that is easier to parse/interpret programatically
- only suggests what we believe is better practice by outputting using a logger which is the standard practice
- would allow for common, modern log shippers to ship your output with our creating message noise, where each println is interpreted as a new log event.

I literally don't see a single reason you would be against it this request.  I've read through your comments multiple times and I still don't see a single argument you have given explaining why . 

> Sorry, but all new features regarding stats (additional stats, pushing stats elsewhere) fall into the scope of FrontLine, our Enterprise version.

Fair enough to that statement, but we're not talking about additional stats, pushing stats or anything about stats.  We're talking about not using a logger for your output which causes problems when using industry standard shipping practices that expect structured logs.

**Comment by slandelle** [comment]
I am sorry to read that my message didn't answer your questions.
We have a consistent strategy regarding our open-source solution and our Enterprise version since the R&D started in 2015. We don't plan to change it for the moment, I hope you understand. Anyway, as I said before, we would be more than pleased to discuss this with you live.
Closing this thread.
