### ISSUE TITLE
Core: Manipulated custom data structures stored in Session

### ISSUE THREAD

**Issue by bchurchill** [gatling/gatling#3660]
**The problem I'm trying to solve** (use-case)
I'm writing tests for a complex web application.  There's a lot of state stored in the session variable.  Unfortunately, my code is beginning to suffer from some maintainability problems because all of the state is being maintained in the same large data structure.  There are two main drawbacks.

The first drawback: there's no typechecking to prevent against easy mistakes; for example, if one stores the string "5" instead of the integer 5, and then tries to read it out later, one encounters a runtime error.  

The second drawback: there's no way to scope the lifetime of a value stored in a session.  For example, suppose the application has two different search boxes, and I want to simulate the user picking one of them, and then use that value.  I might try to write code like this:

```
object FirstSearch {
  val go =  http("search1"). /* ... */.check(bodyString.saveAs("foo"))
}
object SecondSearch {
  val go =  http("search2"). /* ... */.check(bodyString.saveAs("foo"))
}
object SearchAndPick {
  val go = randomSwitch(
      50.0 -> FirstSearch.go,
      50.0 -> SecondSearch.go
  ).exec(session => {
     val foo = session("foo").as[String]
     // do something with foo
     session
 })
}
```

In this case, it might be that the key "foo" is only used in these three objects.  However, I'm polluting the global namespace of the session map.  If the name "foo" were reused somewhere else in the code, an overlooked name conflict could create problems (silently or otherwise).

In both cases, the underlying issue is that scala is a strongly typed language with a lot of features to prevent mistakes, but we cannot use the power of the language when maintaining session state.

**1st Suggestion (simple starting point)**
The easiest thing to do would be to allow framework users to provide their own class for passing around the state, possibly a subclass of Session.  This would at least address the typechecking concern.  I could, for example, create getters and setters for fields of a fixed type, and write functions to operate on the state as needed in an application-specific way.

**2nd Suggestion (a more advanced feature)**
I haven't totally thought this through yet, and there might be some unexpected tradeoffs, but wanted to at least mention the idea of allowing actions/chains to work with a hierarchy of session objects.  In the example above, perhaps FirstSearch.go and SecondSearch.go would "take" an object of class 'MySession < Session' and "return" an object of class 'MyFooSession < MySession'.  Then the anonymous function passed to exec could "take" an object of type 'MyFooSession' and return some other type of session object.  This would help deal with the scoping issue.  The 'MyFooSession' object could have something like a typed 'foo' field which is visible when the 'foo' field is needed, and not elsewhere.  Or, instead of a hierarchy explicitly provided by the user, there might be something clever that can be done with generics, like having a CustomSession[X] object and covariance so that if X < Y then CustomSession[X] < CustomSession[Y].

Hope the problem I'm trying to solve is clear and that one or both of these ideas is helpful.

**Comment by slandelle** [comment]
Hi,

First of all, please understand that Gatling is not a framework but a software. The public API is the DSL methods (not including the return types) and anything that's not documented in an internal that can change without further notice. How `Session` is implemented in an implementation detail and there's no way we'll ever let users bring their own implementation. FYI, Session is a case class, and case classes mustn't be subclasses (we should bother make it final).

As a consequence, Session will always be based on Map, hence untyped.
Moreover, the type safety you're looking for in not a goal for us, as most users really don't care.
Still, we could help implementing programmatic usage of type safe data structures (meaning that things like Gatling EL are out of scope).

On the top of my head, I can think of some place where we would have to provide a new API so you can store into your own way in the Session:

- feeders
- check's saveAs

Now, you have to realize that, even if you use typed data structures, you'll always have to cope with the fact that they will (try to) be populated at runtime, meaning that bad things can happen, typically data captured from `saveAs` could not be there because the request crashed.

I'm still not 100% convinced that what you're trying to achieve is really worth the effort. Maybe some feedback from other users might help.
Scope could be achieved with a naming rule for the attribute keys.

I'm renaming this ticket and leave it open for discussion.

**Comment by slandelle** [comment]
Closing for now due to lack of activity.
