### ISSUE TITLE
Core: always balancer virtual users start up over Akka dispatcher

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3688]
When using injection profiles that group users, eg atOnceUsers, we directly start them from the same dispatcher thread. This causes some components, eg JMS's ThreadLocal Session cache to not properly balance resources.

**Comment by mariaklimenko** [comment]
Could it be a root cause of why I get max 3-5 rps when loading AWS SQS using JMS adaptor? The discussion thread is here: https://groups.google.com/forum/#!topic/gatling/LqK26uVlkAw
If Gatling is posting messages through a single connection then it might be a root cause for my issue... Do you think this fix will address the problem?

**Comment by slandelle** [comment]
Possible. Proper JMS implementations don't need multiple connections because they take advantage of multiplexing. Maybe AWS SQS makes a poor use of connections.

**Comment by mariaklimenko** [comment]
Yeah, seems so. I just added 5 identical scenarios to my setUp (all have unique names though) and got 20 rps instead of 4...

**Comment by slandelle** [comment]
Meaning that scaling connections is not a solution. Having to open 250 connections to achieve a mere 1,000 rps is simply lame for a message broker. Either we’re not using the SQS JMS adapter or it’s just useless for production.
Have you tried reaching out your AWS support ?

**Comment by mariaklimenko** [comment]
Agree, make sense. I will test JMS SQS client in Java and if issue is still there then I report it to AWS guys.
