### ISSUE TITLE
Gatling consumes too much memory for parsing json using jsonPath

### ISSUE THREAD

**Issue by grib0** [gatling/gatling#3855]
My scenario crashes with OOME

I reproduced with the following little uses case :

The json returned by the server is heavy (140Mb). I have only 1 virtual user.
[heavy_json_response_140Mo.zip](https://github.com/gatling/gatling/files/4071680/heavy_json_response_140Mo.zip)

Without check jsonPath, the heap memory used by gatling goes to around 300MB, see visualvm screenshot
![gatling_jvm_without_jsonPath](https://user-images.githubusercontent.com/6506822/72531881-a9895b80-3872-11ea-8fa4-78c5a0abb691.png)

When adding 
`.check(jsonPath("$..volOiseau").notExists` the same simulation consumes up to 2,5GB, still with only one virtual user.

![gatling_jvm_with_jsonPath](https://user-images.githubusercontent.com/6506822/72531882-aa21f200-3872-11ea-8bf3-698578e14daf.png)

With 6 virtual user, the required heap memory goes to 6GB wich seems to high to parse 6 json of 140Mb each

I have 2 workarounds
* use checkIf has I know when the payload response will be too high but i would like to use the check function even with heavy payload 
* use contains as I do not really need a jsonPath for that simple expression

**Comment by slandelle** [comment]
1. Gatling needs to buffer all the bytes in memory => 140MB
2. Once full payload is received, Gatling uses Jackson to load the full JSON tree in memory so JsonPath can traverse it => ~1GB

Nothing we can do here.
JsonPath, XPath and JMesPath are all AST/DOM based.

You can check for yourself:

```java
try (InputStream is = new FileInputStream(YOUR_JSON_FILE)) {
  JsonNode root = new ObjectMapper().readValue(is, JsonNode.class);
  Thread.sleep(10000000); // take heapdump here
}
```

**Comment by grib0** [comment]
Even with check(substring("volOiseau").notExists) the memory goes up to 2,5 Go, analyzing heapdump show 125Mo per thread gatling (5 threads for 5 users) and 600Mo of `io.netty.buffer.PoolChunk`. 
So it's not a json ast/dom problem

Even after the 4 first virtual users have complete, the heap is not release, it sounds like a memory leak in gatling or netty.
Removing the chek and the same simulation stay a 800Mo max heap...

![image](https://user-images.githubusercontent.com/6506822/163430935-99ea7e9e-3617-4a8f-ba7d-afd3e0d1c912.png)

I will try to attach a small simulation to reproduce

**Comment by slandelle** [comment]
> Even with check(substring("volOiseau").notExists)

Well, that doesn't solve the memory consumption in your case: you still need to allocate a huge String.

If you're using Java 8, the internal representation of String uses an UTF-16 byte array, which means 2 bytes per char. If your payload is 140MB, the String will weight 280MB.
Since 11, the underlying byte array can be either US-ASCII or UTF-8, so it should match your 140MB. If you're not already using Java 11 or 17, you should switch.

Then, Netty's memory pooling allocates larger buffers than requested, matching the upper limit for the region.

> Even after the 4 first virtual users have complete, the heap is not release, it sounds like a memory leak in gatling or netty.

No, it's not a leak, it's memory pooling. Netty uses an algorithm similar to jmalloc.

> Removing the check and the same simulation stay a 800Mo max heap...

Yes, because then we never need to allocate a huge contiguous memory to decode your payload: we can discard the chunks.

That being said, we could maybe have a memory efficient substring implementation that doesn't work on String, but uses something like a `java.io.InputStreamReader`.
Contributions welcome! :)
