### ISSUE TITLE
Gatling-charts-highcharts-bundle 3.4.0-M1 Flagged Dependency Upgrades

### ISSUE THREAD

**Issue by msgem** [gatling/gatling#3903]
Hi,

I ran a security vulnerability scan on gatling-charts-highcharts-bundle 3.4.0-M1 & saw some dependencies flagged as medium or high severity (https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/ - scan was run after the 3/12/2020 upload date):
- org.webjars.npm:jquery:3.4.1 (Medium)
		Looks like this was already discussed late 2019 in issue #3838, but this version is also being flagged as an XSS risk (https://snyk.io/vuln/SNYK-JS-JQUERY-567880). It is now recommended to upgrade to 3.5.0 or higher.
	
- org.webjars:highcarts:4.2.3 (High)
		There's a few different js files that are tied to this. Among them is highstock.js, which is located in gatling-charts-highcharts-3.4.0-M1.jar, io.gatling.charts.assets.js directory. According to the vulnerability report, it's also flagging what I presume to be its transitive dependencies: highstock.src.js, highcharts.js, highcharts.src.js, highmaps.js, and highmaps.src.js. This version is flagged as a high ReDoS risk (https://snyk.io/vuln/maven:org.webjars%3Ahighcharts). Version 6.1.0 or higher no longer has such issues.
	
Can these be updated & another gatling-charts-highcharts-bundle uploaded?

Thanks.

**Comment by slandelle** [comment]
I've just upgraded jQuery to 3.5.1.

Regarding highcharts, we have no plans on upgrading atm. There's no security issue here: the generated reports are only meant to be loaded locally from the filesystem, not from a remote server.

**Comment by msgem** [comment]
Thank you for looking into this so quickly and upgrading jQuery. And correct, all reports are to be opened locally, I just wanted to check highcharts since it was marked as high severity.

Do you mind uploading a new gatling-charts-highcharts-bundle to reflect the latest change?

**Comment by slandelle** [comment]
3.4.0 should be released between 1 and 2 months.
You're not even supposed to be using 3.4.0-M1 which is an undocumented milestone only released for internal usage. Latest official release is 3.3.1.

**Comment by msgem** [comment]
I've used 3.3.1 but saw that 3.4.0 was in the works and wanted to see if any vulnerabilities could be handled while it was still in-progress. Thank you for clarifying though, I'll wait until the release date to get the final bundle. I'm presuming it would still contain the highcharts 4.2.3 - as you mentioned, there's no plans to upgrade it at the moment, but is this a possibility going forward? Or will it remain static as far as you can tell?

**Comment by slandelle** [comment]
> I'm presuming it would still contain the highcharts 4.2.3 - as you mentioned, there's no plans to upgrade it at the moment, but is this a possibility going forward? Or will it remain static as far as you can tell?

Highcharts licensing is "complicated".

We picked this library a long time ago when we started this project. We originally thought we would be fine and fall in their OEM license (hence free) because we're open-source. Sadly, it turned out lawyers mean a different thing with "non-profit organizations".

We ended up purchasing a license so we can **redistribute** the library (for free) in an unlimited fashion. This last point is crucial, and it was at that time a bit complicated to make the sales person understand we couldn't pay millions of dollars.

Hopefully, we ended up with an agreement and a reasonable price, at the cost of putting on the module that ships Highcharts a non open-source license (see our [FAQ](https://gatling.io/docs/current/project/faq/)) so Gatling end-users are forbidden from modifying Gatling reports with having their own Highcharts license.

We've renewed the license for upgrades for several years but have stopped doing so (explaining the original deal to the new sales person was cumbersome). We're currently shipping the last version we can according to our last purchased license update.

At this point, as long as the version we currently have works with latest browsers updates, or Highsoft doesn't grant free licenses to open-source projects, we don't plan to purchase a license update that would let us upgrade.

**Comment by msgem** [comment]
Ok, I wasn't aware of the licensing factor (or its joys of legal subjectivity); that makes more sense now.

I read those FAQ notes and saw the following:
> If anyone can come with an Apache 2 licensed solution that’s as sexy and plug-and-play as Highcharts and Highstock, we’d gladly make it the default implementation and integrate it into the main project!

I soon began looking for highcharts alternatives, hence my rather late response. Many tools I'm seeing have MIT license instead of Apache 2 - so far, the only reasonable one with Apache license that I could find is Grafana, which perhaps might work since Gatling allows for Graphite integration, but not sure.

With all that being said, you all have almost certainly gone through this research already as well. If I happen to find anything that can be discussed, however, I'll be just as glad to let you know.

Thanks again for all your help.

**Comment by slandelle** [comment]
Grafana is a dashboard software, not a standalone JS charts library.

Anyway, we really don't have the bandwidth for migrating the charts to a different library an risk breaking something that works. We'll only do so if it becomes a blocker, typically if the version we have stops working with latest browsers updates.

**Comment by msgem** [comment]
Good point, that is understandable - I appreciate your explanation on this.
