### ISSUE TITLE
No tags or branches in repo for releases

### ISSUE THREAD

**Issue by luvarqpp** [gatling/gatling#3906]
Hello,
I like gatling project, but I would like to see some improvements regarding its release management. Project is evolving without much compatibility between versions and thus to extend it (in any way) is a bit harder. For example I have coded AMQP (with proper request/reply support) plugin/protocol and it is not usable after dependency version change. This behavior is OK, as I can depend on some specific version and I have sources for this version.

I would like to have tags (or branches) in github repo for all [publicly released/accessible gatling versions](https://mvnrepository.com/artifact/io.gatling.highcharts/gatling-charts-highcharts). I.e. I can migrate [prometheus datawriter](https://github.com/bmaguireibm/gatling-prometheus-datawriter) to current version easyli. Now I am struggling to have right "Engine.scala" version, correct `GatlingConfiguration` class (compatible with runner), e.t.c.

Please add tags for all released gatling libraries to github repo.

**Comment by slandelle** [comment]
User visible changes are documented in [our migration guides](https://gatling.io/docs/current/migration_guides/), which is enough for standard usage.

The components you're referring to are internals and subjects to changes at any time without any further notice.

Then, regarding extending, it can mean different things:

* choosing to develop a independent third party instead of contributing upstream. This sure comes at the price: maintenance. If such plugin was to be contributed upstream, we could maintain it ourselves and it would help our broader community.
* forking to workaround our rule that improvements fall in the scope of FrontLine, typically stats and reporting. That's entirely the author of such unfriendly fork's responsibility. This is what the project you're referring to is. If you want Prometheus integration, you can use the official Prometheus Graphite exporter instead.

To some extent, we can answer questions from authors of independent yet non-unfriendly third parties regarding internals changes. But we won't do any kind of change and extra work that doesn't serve a purpose in official Gatling components.

I hope you'll understand.

**Comment by luvarqpp** [comment]
Thanks for long and clarifying answer. I see it now and I agree. I hit given prometheus plugin because of "cheap way to add some ad-hoc test to monitoring". I have not found prometheus graphite exporter and it seems it would solve my task.

PS: Would you be interested in PR with some "javadoc" mostly for http DSL? I miss it and frequently to have a look at gatling cheat sheet. Perhaps I would mostly copy/paste given things (which is not ideal) and add http link directly to cheat sheet. If something is nontrivial to use (for example `checkIf`), I would add also some sample code.

PS2: Are you interested also in contribution for "weird" protocols? I have on my mind for example DLMS. I will (in a few months) consider implementing one basic perf test using gatling. Have on mind, that DLMS is huge protocol and I will implement just some basic things for simulating many gas/power/water meters.

**Comment by slandelle** [comment]
Thanks for your understanding.

> Would you be interested in PR with some "javadoc" mostly for http DSL?

Absolutely! Please beware [scaladoc's syntax](https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html) is slightly different from javadoc's. Also, we're yet to switch to latest Scala major version so some syntax might no work yet.

> Are you interested also in contribution for "weird" protocols?

Sadly, when there's no market, no. When we accept contribution for new protocols (WebSocket and JMS originated this way), we have to learn the protocol so we can maintain ourselves should the original contributor stop contributing, be able to run tests, etc. This is an investment, and we can only afford doing so if the user base is large enough.
Typically, we'd be very grateful for contributions on AMQP, Kafka, gRPC...
