### ISSUE TITLE
HTTP: periodically send WebSocket heartbeat Data frames, a la socket.io

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3929]
socket.io uses a specific heartbeat mechanism based on Data frames (as JavaScript WebSocket API doesn't have access to Ping and Pong frames). See https://socket.io/docs/ "Disconnection detection".
Client will send `2` to server that will respond with `3`.
Default period is 25s.

As socket.io is a very standard WebSocket framework, it would be nice to support such mechanism out of the box.

**Comment by katerina-stepanova** [comment]
Similar mechanism exists in STOMP protocol as well, but with different heartbeat messages:
Message from server: a["\n"]
Message client responds with: ["\n"]

STOMP docs: https://stomp.github.io/stomp-specification-1.2.html

**Comment by slandelle** [comment]
@katerina-stepanova thanks for the info

**Comment by pschiffe** [comment]
Hello @slandelle ,

with Engine.IO 4 release, socket.io reversed heartbeat mechanism. Now server is sending `2` as ping, and expects clients to reply with `3` - https://socket.io/blog/engine-io-4-release/

Our app heavily utilizes socket.io and this change is a nightmare to work with in gatling. Before, we were managing pings by ourselves, but at least we were in control when to send them. Now, I'm sending blind pongs and it kinda works, but not really in complex scenarios.

There are two main issues:
1. I'm not always listening on websockets, and it's not even possible to do with gatling, since every user is single-threaded / has only serial execution of commands.
2. I'm not sure if it's possible to listen for 2 kinds of stream messages and react differently to them.

I found https://github.com/gatling/gatling/blob/main/gatling-http-client/src/main/java/io/gatling/http/client/impl/WebSocketHandler.java#L140 and maybe something like this could fix it, but there should by also some kind of socket.io detection as well I guess..
```
if (frame instanceof TextWebSocketFrame) {
  if (frame.text() == "2") {
    ctx.writeAndFlush(new TextWebSocketFrame("3"));
  } else {
    wsListener.onTextFrame((TextWebSocketFrame) frame);
  }
```
