### ISSUE TITLE
HTTP: keep original Referer on redirect

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3934]
Behavior doesn’t seem to be specified, but it looks like there’s a consensus amongst browsers and Referer header shouldn’t be updated on redirect, see https://stackoverflow.com/questions/2158283/will-a-302-redirect-maintain-the-referer-string/5441932#5441932

**Comment by anirudhwarrier** [comment]
@slandelle 
With respect to the community thread at [Unable to set HTTP Referer Header when request has redirect 30X response](https://groups.google.com/g/gatling/c/dgQQrbSyIz0)

I want to clarify the following.

`Gatling Client -> Request A (Actual request) -> Request B (Redirect request)`

I understand that this bug is to maintain the original Referer in the redirected request (Request B)

However, my concern is that the original request's (Request A) Referer header is not set as specified in the code.

**Comment by slandelle** [comment]
@anirudhwarrier I tried your sample and can't reproduce your issue:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
first: OK 
=========================
Session:
Session(dummy,1,Map(gatling.http.ssl.sslContexts -> io.gatling.http.util.SslContexts@768a5784, gatling.http.cache.dns -> io.gatling.http.cache.NoopCloseNameResolver@48919221, gatling.http.cache.baseUrl -> http://google.com),OK,List(),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$425/0x00000008004f8040@3e84623,io.netty.channel.nio.NioEventLoop@2caf6912)
=========================
HTTP request:
GET http://google.com/
headers=
referer: https://facebook.com
accept: */*
host: www.google.com
=========================
HTTP response:
status=
301 Moved Permanently
headers= 
Location: http://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Tue, 25 Aug 2020 19:34:36 GMT
Expires: Thu, 24 Sep 2020 19:34:36 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 219
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN

body=
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

<<<<<<<<<<<<<<<<<<<<<<<<<
```

I suspect you're using an old Gatling version.
