### ISSUE TITLE
Gradle plugin: detect all/more of logback possible user provided configuration

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#3952]
Currently, only `logback.xml` file is detected. But logback support other configuration options:

Another issue is that existing logback detection is bound to hardcoded path (src/gatling/resources) and neglects [options](http://logback.qos.ch/manual/configuration.html#automaticConf) other than logback.xml, eg `logback.groovy` and `logback-test.xml`.

**Comment by eshepelyuk** [comment]
This can't be implemented separately from #3951 , since its both the same component.

Copying the description here 

### Current issue

* Logback generation happens at `doLast` closure of `processGatlingResources` task. When there's no gatling resource, i.e. default folder `src/gatling/resource` missing - the logback.xml doesn't get generated.

### Scope of changes

* `LogbackConfigTaskAction` should be called as `doLast` closure of another task.
* proposal is to call it after successful compilation of Gatling simulation
* task name is `gatlingClasses`

**Comment by eshepelyuk** [comment]
Started working on the issue.

**Comment by slandelle** [comment]
Closed by https://github.com/gatling/gatling-gradle-plugin/commit/e6196109616d38a89721423d98bcbe411373d55c

**Comment by eshepelyuk** [comment]
@slandelle I'm curios, why the issue was not autoclosed after the PR merge. 
Do you have an idea ?

**Comment by slandelle** [comment]
@eshepelyuk Autoclose is only triggered when keyword and issue number are in the commit message title (first line), not in the body (lines after the first one).

`fix: logback.xml detection and generation, close gatling/gatling#3951, close gatling/gatling#3952` would have worked.
