### ISSUE TITLE
Feature request: do not save and show requests

### ISSUE THREAD

**Issue by tomers** [gatling/gatling#4006]
When running simulation for a long period of time and for a long list of URLs, the HTML report becomes very big, and in the report folder there are many `req_https*` files. In my case I am not interested in that resolution, and I only care about the histogram graphs. 
Would it be possible to pass a parameter to gatling to disable creation of the request files, and also hide the requests table (the orange Statistics table) in the report?

**Comment by slandelle** [comment]
Your problem is that you're generating way too many request names. That's an issue with your test design.
Don't use the url as request name and if you're using `inferHtmlResources`, use `nameInferredHtmlResources` and friends to squash them.

Please read https://gatling.io/docs/current/http/http_protocol/#resource-inferring
