### ISSUE TITLE
SBT plugin: return non zero code when trying to run nonexistent simulation

### ISSUE THREAD

**Issue by eevulution** [gatling/gatling#4042]
### The environment:
**OS:** Ubuntu 16.04.6 LTS
**Scala:** 2.13.4
**Gatling:** 3.5.1
**SBT:** 1.4.7
**Gatling-sbt-plugin:** 3.2.1
**Running methods:** Travis CI, Gitlab CI, locally in sbt

### The steps
1. Create any Gatling project in sbt: here's the [example](https://github.com/eevulution/gatling-sbt-plugin-demo) which has Travis CI where you can see the bug in action.
2. Run `sbt 'gatling:testOnly <simulationName>'` with literally any simulation name that doesn't exist.

### The problem
See [the run](https://travis-ci.com/github/eevulution/gatling-sbt-plugin-demo/builds/215587840).

**Current result:**
```
[info]   Compilation completed in 13.51s.
[info] done compiling
[info] Simulation(s) execution ended.
[info] No tests to run for Gatling / testOnly
[success] Total time: 21 s, completed Feb 1, 2021, 12:16:41 PM
```
The command `sbt 'gatling:testOnly computerdatabase.NonexistentSimulation'` exited with return code `0`.

**Expected result:**
The command `sbt 'gatling:testOnly computerdatabase.NonexistentSimulation'` exited with non zero return code as it's clearly not a successful run.

**Comment by slandelle** [comment]
Hello
contributions welcome!

**Comment by slandelle** [comment]
@Isammoc gtling-sbt is based on sbt's test framework. Do you know if we have any way to crash if there's no detected test classes?

**Comment by Isammoc** [comment]
First time I navigate in this code, so I'm not sure what I see, yet.

Indeed, we do have a [`GatlingFramework`](https://github.com/gatling/gatling/blob/main/gatling-test-framework/src/main/scala/io/gatling/sbt/GatlingFramework.scala) that extends `sbt.testing.Framework`.

First, we should ensure that we do have a `taskDef` argument in [`GatlingRunner.scala#L32`](https://github.com/gatling/gatling/blob/main/gatling-test-framework/src/main/scala/io/gatling/sbt/GatlingRunner.scala#L32)

Not tested, but I think we do have a taskDef with the `NonExistentSimulation` className.

And the className should be given in a taskDef in [`GatlingTask.scala#L44-L45`](https://github.com/gatling/gatling/blob/main/gatling-test-framework/src/main/scala/io/gatling/sbt/GatlingTask.scala#L44-L45)

We manage status code in this, perhaps should we have more fined grain in our process.

If there is no class provided => as currently, ie: simulation if it's alone or ask for user to choose.
If there is a className provided => if no matching in the simulation list, return an error.



But I'm concerned by this behavior generally speaking. Should we really fail in that case?

Let's a `root` project we 2 submodules `subA` and `subB`.
When we execute `gatling:testOnly subA.simulation1` for a simulation that only exists in `subA` submodule, we expect that `sub1.simulation1` is ran correctly and no other error will interfere.
But if change the behavior as requested in this issue. The `root` submodule that aggregates both `subA` and `subB` will dispatch the same task to both submodules, and will aggregate the result (one success for `subA` and ... one error for `subB` because the simulation does not exist in `subB`)

I don't think this behavior is suitable either.

**Comment by slandelle** [comment]
Same explanation as #4105. This is idiomatic sbt test framework. `testOnly` takes a pattern and doesn't fail when no tests are executed.
