### ISSUE TITLE
Dependency vulnerability gatling-http-client  -> netty-codec-http

### ISSUE THREAD

**Issue by jobmulder** [gatling/gatling#4050]
gatling version 3.5.1
`gatling-http-client` has dependency on `netty-handler-proxy:4.1.58.Final` which has a vulnerability https://snyk.io/vuln/SNYK-JAVA-IONETTY-1070799.
This can be solved by upgrading to version `4.1.59.Final`.

```
  Upgrade io.netty:netty-handler-proxy@4.1.58.Final to io.netty:netty-handler-proxy@4.1.59.Final to fix
  ✗ Information Disclosure (new) [Medium Severity][https://snyk.io/vuln/SNYK-JAVA-IONETTY-1070799] in io.netty:netty-codec-http@4.1.58.Final
    introduced by io.netty:netty-handler-proxy@4.1.58.Final > io.netty:netty-codec-http@4.1.58.Final and 3 other path(s)
```

**Comment by slandelle** [comment]
This vulnerability is server side while Gatling is client side.

**Comment by DerkSchooltink** [comment]
> This vulnerability is server side while Gatling is client side.

Are you sure? https://github.com/gatling/gatling/commit/285d9d9ed2745c5bb7dfcdcd79ecff260096cf83

Issue seems to be prematurely shot-down. It was already fixed but not yet released, but it is not a server-side issue?

**Comment by slandelle** [comment]
Yes I'm sure (I'm a Netty contributer and was in the loop before the CVE was made official).

Please take some time to read the CVE: the affected component is the **multipart decoder** that can be used to decode multipart request bodies on the server side.

Gatling itself is not impacted, so there's no rush in having a release.

**Comment by DerkSchooltink** [comment]
> Yes I'm sure (I'm a Netty contributer and was in the loop before the CVE was made official).
> 
> Please take some time to read the CVE: the affected component is the **multipart decoder** that can be used to decode multipart request bodies on the server side.
> 
> Gatling itself is not impacted, so there's no rush in having a release.

Okay I can understand that Gatling is not directly impacted by this CVE, but since it was important enough to fix it with the commit I referenced before I would've expected a different answer here to the original issue: the dependency has been upgraded and a release will come later. 

I don't mean to come off as rude but closing the issue with only saying that the issue is "serverside" (I think this could have been better described as "does not affect Gatling", as multipart decoders are not inherently something server-sided) leaves the issuer to be desired with a more complete answer.

For now I guess the solution would be to silence the issue and await the next release of the Gradle plugin. 😄

**Comment by slandelle** [comment]
> since it was important enough to fix it with the commit I referenced before

Absolutely not. Like lots of projects nowadays, we have automated pull requests for upgrading all our JVM dependencies, using scala-steward. We didn't upgrade because of this CVE and [this release contains other improvements](https://netty.io/news/2021/02/08/4-1-59-Final.html).

> I don't mean to come off as rude but closing the issue with only saying that the issue is "serverside"...

Sorry if my answer was short. But all the information is publicly available in the CVE description.

With the rise of automated static code and dependency analysis tools, there are more and more users opening issues without any prior thought about the actual impact, eg:

* https://github.com/netty/netty/issues/10430
* https://github.com/netty/netty/issues/10362
* https://github.com/netty/netty/issues/10369
* https://github.com/netty/netty/issues/9930

Please understand the extra burden on maintainers.
