### ISSUE TITLE
Gatling takes too long time in the first request

### ISSUE THREAD

**Issue by Curt900701** [gatling/gatling#4129]
Hi could you help to confirm if gatling can reduce response time in first request?

Steps to reproduce:
OS: MACOS 11.5

1. Download Open-Source tool from [Gatling](https://gatling.io/open-source/?utm_campaign=FrontLine&utm_source=ppc&utm_medium=google&utm_content=search&gclid=EAIaIQobChMIq4efvunG8gIVhFVgCh09EAHCEAAYASABEgKuDvD_BwE)
2. Unzip the open-source tool and execute computerdatabase.BasicSimulation via gatling.sh
3. Check result , refer to below screenshot
=> The first request takes more that 3500ms
![截屏2021-08-23 下午5 29 07](https://user-images.githubusercontent.com/43240691/130424604-de318e0b-141f-46a3-8a22-048e6e541adc.png)
4. Try to add warmUp to http but still has the same issue
`val httpProtocol = http.warmUp("http://www.google.com")`

**Comment by slandelle** [comment]
This is most likely an issue with your computer (eg other processes eating all the CPU at the same time) or your network (maybe a corporate network, or the Great Firewall, as I see you're in China). Here's what I have on my side (tested on MacOS 11.4 with Java 8u302 and 16.0.2):

<img width="900" alt="Screenshot 2021-08-23 at 12 07 22" src="https://user-images.githubusercontent.com/849197/130430167-9778e3a2-d9ee-4e13-8ef9-96875baba447.png">

Sorry, but I'm afraid there's nothing we can do, the issue is not on our side.

**Comment by Curt900701** [comment]
@slandelle Thanks for the confirmation, no sure if it's related to network (Using postman with the first request, takes about 421ms)

Regarding your screenshot, my understanding is if using warmup, the response time of first request should be same as others(around 80 ~ 90ms), is that correct? 
In your screenshot it is 174ms, about 2 times longer than other apis.

**Comment by slandelle** [comment]
Also, check that your `/etc/hosts` is not broken. You must have entries such as:

```
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
```

If not, you must add them.

> Regarding your screenshot, my understanding is if using warmup, the response time of first request should be same as others(around 80 ~ 90ms), is that correct?

It's not. In this use case, the first request will have to perform a DNS resolution and then open a TCP socket, while the next request will ride one this first keep-alive HTTP connection.
