### ISSUE TITLE
Jenkins OSS Plugin: gatlingArchive() step do not support running on nodes

### ISSUE THREAD

**Issue by aytuncbeken** [gatling/gatling#4133]
Hi,

When the gatlingArchive() step is used in pipeline, It tries to create a directory under the jobs directory in Jenkins.
For Example: ```/var/lib/jenkins/jobs/gatling/jobs/galing-job/builds/22/simulations/createandmodifyapplicationssimulation-20210903124246814```
However, this directory only exists in the master node.
When this step is used in a node (persistent or container), as this directory ```/var/lib/jenkins/jobs``` only exists in master node, gatling fails with the below error

```
Could not create simulation archive directory '/var/lib/jenkins/jobs/gatling/jobs/galing-job/builds/22/simulations/createandmodifyapplicationssimulation-20210903124246814'
No newer Gatling reports to archive.
```

**Comment by slandelle** [comment]
Hi,

You don't mention the version you're using. Please make sure you're using the latest version.

If you still have an issue with the latest version, I'm afraid we won't work on this ourselves, due to lack of bandwidth and the fact that Gatling Enterprise use a different plugin that doesn't make use of Jenkins nodes as load injectors.

Contributions welcome, then.

**Comment by aytuncbeken** [comment]
Hi 

The latest version is being used. Sorry to hear. Thanks.

**Comment by slandelle** [comment]
Idle, closing for now.
