### ISSUE TITLE
Core: Distributed mode

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#415]
Have a distributed mode for getting over the hardware and OS limits.

**Comment by mauaht** [comment]
It does not appear that an implementation has been decided upon, so I thought I'd add my thoughts from the point of view of a performance tester with over 15 years experience, mostly with LoadRunner but also other commercial tools and open source (OpenSTA), and developer that has worked with Scala, Java, Cassandra and ElasticSearch.

Cassandra and MongoDB have already been suggested for a test artifact data store. I suggest ElasticSearch for the following reasons:
- Provides convenient storage for scripts, test data, timing results, server metrics, and reports. 
- Able to use indices to manage data volume and currency by storing test scripts, test data and results in different indices. Test results can be easily archived out, by closing test result indices, while keeping indices containing test inputs (scripts, test data) live. Similarly, test data can be refreshed by closing old test data indices and building new ones so that test script data for feeders matches data in the target test environment. Use ES index aliases to make this transparent to test scripts/scenarios.            
- ES has very fast read performance. So an ES feeder can be used feed test data from ElasticSearch into running vusers. The number of replicas per ES shard can be set to give the desired read performance. It is even possible to run ES nodes on the same machine as Gatling nodes with ES data replicated to those nodes so that ES feeders read from a local copy of the ES index shard.
- Search and analytics capability for analysing timing results and correlating these with server metrics. In particular, there is the possibility to leverage the ELK stack (ElasticSearch, LogStash, Kibana) which already provides the ability to consolidate and analyse server metrics (eg using collectd) and log file data from many different sources. This alone should be sufficient motivation because it opens up huge potential for a flexible test analytics capability. 
- REST API    

Following are some thoughts on an ES based implementation

Test execution console
- Client side HTML5 web application that calls HTTP Rest services running on each node in the cluster.
- Implement a range of Gatling HTTP REST services to control test execution. 
- Leverage Kibana for real time monitoring and post run analytics.

Cluster Script and Test Run Controller
- Cluster script defines the cluster wide test configuration and references the scenario scripts to be executed by load generators.
- Compile and run as cluster singleton. Cluster must be able to route requests from web app console to this cluster singleton 
- Partitions the workload among the selected load generators and starts execution on those load generators. 
- Provides a real time view of the status of the running test (eg. aggregated response times) and a coordination point for modifying a running test (eg increasing/decreasing the load, stopping the test run).
- REST service for discovering all running tests and the nodes on which the individual test controllers are running.
   
Load generators
- Run independently without any central synchronization once started (minimize network chatter)   
- Write all timing results to a local file during execution and upload to ES after test execution completes (this is what LoadRunner does). 
- Send sampling of timing results to ES during execution for real time monitoring. Allow samples to be skipped if the generator is heavily loaded, ie. prioritize load generation over sampling. 
- Write timing results and other events (checks and errors) to ES in Logstash format so Kibana can display it.

ES Feeder
- Retrieving blocks of test data records which it caches in memory and feeds to vusers when requested. 
- Configurable threshold to trigger retrieval of the next batch so that it always has data in memory ready to be feed to vusers. (users are never blocked while data is loaded from ES)
- Replicate ES test data indices to load generators so that feeders read test data from local copies.
- Use ES optimistic concurrency control on "data allocation tables" to prevent the same data blocks being allocated/claimed by more than one load generator.
(LoadRunner controller allocates blocks of sequential rows from data files to vusers at the start of a test. This can be limiting and makes management of consumable test data, as found when testing workflow applications, difficult. The proposed approach is more flexible because blocks are allocated on the fly as needed and if a test is stopped the next run can start using data from where the previous aborted run left off. )

**Comment by jedesah** [comment]
Is there any work being done on this front? Would a contribution be welcome?

**Comment by slandelle** [comment]
@jedesah Hi! Yes, there's work in progress, but it will be part of a commercial product ;)
Please get in touch at contact@gatling.io if you're interested.

**Comment by slandelle** [comment]
Done in commercial product

**Comment by aidylewis** [comment]
Is it possible to trial/test a binary?

**Comment by Elufimov** [comment]
@slandelle Where i can read about commercial version? =)

**Comment by slandelle** [comment]
We're not public yet, sorry. If you're interested, please "officially" get in touch on contact@gatling.io.

**Comment by ece351** [comment]
Please let us know if the distributed implementation is public yet. I need that bad for one of internal poc using Influxdb.

**Comment by slandelle** [comment]
Distributed mode is only available in FrontLine, our commercial product. And it doesn't store into InfluxDB, but a Grafana integration will come.
