### ISSUE TITLE
Issue in setting null value from a csv feeder to a .txt template using .jsonStringify()

### ISSUE THREAD

**Issue by anuragp09** [gatling/gatling#4184]
Running the simulation in Windows OS.
I am using gatling gradle plugin version 3.7.3 in my build.gradle file:

I have a feeder.csv like below:
```
rank,firstName,lastName,hobby
1,Jack,Smith,reading
2,Sam,,running
```
I have a template.txt like below:
````
{
  "rank": #{rank},
  "firstName": #{firstName.jsonStringify()},
  "lastName": #{lastName.jsonStringify()},
  "hobby": #{hobby.jsonStringify()}
}
````

I am expecting lastName to be set as null for the second record of the csv, but it is setting the lastName as  empty string "".
Also if I have the literal null in my csv, the lastName is setting to "null".

```
.body(ElFileBody("template.txt"))
.asJson
```

**Comment by slandelle** [comment]
Wrong expectation then.
You have an empty String in your csv file so that’s what you have in your payload.
One possible solution is to transform your feeder’s content and turn empty Strings values into null, see https://gatling.io/docs/gatling/reference/current/core/session/feeder/#transform

Also, next time, please use the community group instead of the bugtracker.
