### ISSUE TITLE
HTTP: Ability to pass close code to WebSocket close method

### ISSUE THREAD

**Issue by Rybenka** [gatling/gatling#4204]
Hello,

We observed that in onClose event on websocket server netty is returning close code -1
Would it be possible to add another variant of `close` method so thait it's possible to pass the close code from Gatling test, so that we can do:

`.exec(ws("Close WS").close(some_close_code))`

currently we can only close without any parameter, like here:

`.exec(ws("Close WS").close)`
 which results in obtaining close code -1 on websocket server's side.

Please let me know if you need some more information/explanation.

**Comment by Rybenka** [comment]
Here is a  demo app with Gatling test to reproduce it: https://github.com/Rybenka/examplewss/tree/closeCodeDemo
Just follow the instructions in README

**Comment by slandelle** [comment]
Hello,

Thanks for reporting.

I think there are 2 things here:
* we're sending an empty close frame. IMHO, this is a bug. We should send a frame with a 1000 code. This will be fixed in the 3.7 branch, see https://github.com/gatling/gatling/issues/4205
* we don't provide the ability to specify the status (hence other than 1000). This is a feature that can only be shipped in 3.8.

**Comment by Rybenka** [comment]
@slandelle , as per the comment "This is a feature that can only be shipped in 3.8" - does it mean that this feature is already on 3.8 roadmap or should I create a separate issue for that?

**Comment by slandelle** [comment]
@Rybenka The code is already pushed into the main branch, but it will only be shipped in an official release as of Gatling 3.8, which is only likely to happen in ~2 months.
