### ISSUE TITLE
JMS: report messageId on timeout

### ISSUE THREAD

**Issue by alex3dm** [gatling/gatling#4206]
I can override the io.gatling.jms.client class.Tracker?
During timeout, it is necessary to log the messageId of the request. And how to do it?

**Comment by slandelle** [comment]
> I can override the io.gatling.jms.client class.Tracker?

No, it's not possible.

> During timeout, it is necessary to log the messageId of the request. And how to do it?

I don't think it's feasible atm.
Also, I don't know/understand what's the use case there.

**Comment by alex3dm** [comment]
use case: 
When testing the application, I feed the load through Gatling and there are single timeouts. There are no errors in the application Logs.

**Comment by slandelle** [comment]
A timeout doesn't necessarily mean an application error. It might just mean the application doesn't handle the message in due time, or even lose it silently.
Anyway, we don't have this feature atm.

Contributions welcome, but please explain your strategy first.

**Comment by oddfrost** [comment]
If you can not check message processing status in system (in database maybe?) you can try to write your own [JmsMessageMatcher](https://github.com/gatling/gatling/blob/main/gatling-jms/src/main/scala/io/gatling/jms/protocol/JmsMessageMatcher.scala) or enable logging for JMS (as for me, i don't like its logging because it is not writing whole text of the message). You can use hash table with message id and timestamp to save outgoing messages and check for message id on receive. Then you can log message id if response time is greater than your timeout. Or you can check on receive if there are any timestamps which were created long time ago and log them (but it is better to do at the end of the test).

**Comment by slandelle** [comment]
Idle, closing for now.
