### ISSUE TITLE
Core: Gatling 3.7.5 pulls unexpected httpcore dependency that blocks adding to to Enterprise package

### ISSUE THREAD

**Issue by vrawat79** [gatling/gatling#4214]
Bug: For a project, using Gatling with "aws java sdk" but getting a run time error of ClassNotFound for classes in httpcore.jar (e.g. ConnectionReuseStrategy.class). Even though "Gatling Maven plugin" packaged aws-java sdk in the shaded.jar, the runtime dependency of http.jar was not packaged. 

To replicate / troubleshoot I did the below setup separately as well. 
Step 1. Cloned gatling-maven-plugin-demo from https://github.com/gatling/gatling-maven-plugin-demo
Step 2: Added dependency for apache httpcore as shown below. 

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.15</version>
		</dependency>
Step 3: Ran mvn gatling:enterprisePackage 
Step 4. Extracted the "gatling-maven-plugin-demo-java-3.7.5-shaded.jar" and it doesn't have the httpcore library.

Please note that any other dependency like gson below is getting packaged. But httpcore.jar is not getting packaged.

                <dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.0</version>
		</dependency>

This issue is leading to Run Time Error of ClassNotFound for httpcore.jar.

**Comment by slandelle** [comment]
That's a regression introduced in Gatling 3.7.5 because of an upgrade of Saxon-HE that unexpectedly changed our dependency tree. We'll fix fix this in the next release. Until then, please revert to Gatling 3.7.4.

Thanks for reporting!

**Comment by vrawat79** [comment]
Thank you. Reverting to Gatling 3.7.4 resolves the current blocker.

**Comment by slandelle** [comment]
Since 11, Saxon has a hard dependency on `xmlresolver`. I couldn't find a way to bypass it, it the first thing happening in `net.sf.saxon.Configuration`.

Because of this move, it now pulls the following dependencies:
* xmlresolver: 150259 B
* xmlresolver/data classifier: 1027759 B
* httpclient: 780321 B
* httpcore: 328324 B
* commons-logging: 61829 B
* commons-codec: 353793 B
* xml-apis: 109318 B

That's a grand total of 2811603 B, hence ~2.7MB of extra weight we don't want.
Moreover, we really don't want to ship and extra HTTP client than our internal one.

It try to report the issue to Saxonica but wasn't able to re-activate my account on their Developper forum.

I guess we're stuck with 10.6 and will have to live with it.
