### ISSUE TITLE
Core: add random numbers generators

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4316]
Similar to #4315.

Original discussion here: #4305.

Let's first discuss the syntax here @Amerousful @shoaib42.

**Comment by slandelle** [comment]
Original proposal from @Amerousful in https://github.com/gatling/gatling/pull/4311:

```
"#{randomNumber(10)}"
"#{randomNumber(5,10)}"
"#{randomNumber(5, max)}"
"#{randomNumber(5, maxL)}"
```

My comments on this:
1. all those would generate `Long`. Shouldn't we have distinct `randomInt` and `randomDouble`?
2. I'm not found of the magic `max` and `maxL`. I'd rather stick to explicit values.

I would suggest:

```
"#{randomInt()}" // full int range  
"#{randomInt(10)}" // between 0 and 10 inclusive
"#{randomInt(5, 10)}" // between 5 and 10 inclusive
"#{randomLong()}" // full long range   
"#{randomLong(10)}" // between 0 and 10 inclusive
"#{randomLong(5, 10)}" // between 5 and 10 inclusive
```

WDYT?

**Comment by gemiusz** [comment]
I want to add something from my side:
I think that `randomDouble` will be beter but how to handle a precision if someone want to have 3.14 (not 3.1415...) - do you have thinking about using `BigDecimal` to handle all numbers ?
How about negative values ?
I don't thik that `full range` is a good idea I thik that `between X and Y` it's only good solution - this will be clear how it works when someone will see it.

**Comment by shoaib42** [comment]
Late to join the party, here are my thoughts. I've listed them in the table below

| func/method  | use case | other requirements |
| ------------- | ------------- | ------------- |
| `randomLong()`  | full range -ve to +ve, counts/random ids ||
| `randomLong(min, max)`  | enumerated codes, "device type" etc, `randomLong(0, 10)` covers `randomLong(10)` ||
| `randomInt(min, max)`  |same as above||
| `randomDouble(min, max)`  | longitutde, latitude, we need negative floating points (OOTB is not covered), Device send slocation and response depends on this, might be a hot key that gets involved that needs stressing| needs +ve and -ve |
| `randomDouble(min, max, round)`  | currency, ending up in a DECIMAL in db| needs +ve and -ve |

I feel that adding too many flavours fo randomLong/randomDouble will turn into a long list for the endUser to know. That's my opinion, thought I throw that in.

If it were not for gRPC I would have said `randomLong(min,max)` is enough since all of it gets converted to TEXT anyways. What do you guys think about keeping the following list only

(Let's avoid the word precision with floating point numbers in this context. Someone will nit pick on that.)

| func/method | defaults |
| ------------- | ------------- |
| `randomLong()`||
| `randomLong(min, max)`||
| `randomInt()`||
| `randomInt(min, max)`||
| `randomDouble(min, max, round)`| round = -1, no rounding|
| `randomFloat(min, max, round)`| round = -1, no rounding|

Now for naming the EL function names, should we do `randomInt()`, `randomLong()` or something shorter, yet understandable, like `randInt()` or `rInt()`

**Comment by Amerousful** [comment]
@slandelle 
1. Yep, you're totally right about `Long`. I also realized this after a while, so locally I have the version which returns AnyVal.
2. About `max` and `maxL` I thought that will be preferable for the user instead pass the explicit value. I mean case when your `min` above zero. And in my case, I use one unified method instead methods for each number type. 
**But on the other side, we pay for that by performance and extra logic.** It's all about choice convenience vs performance. 

Nonetheless, your suggestion is good and I like it.

Also, there is a question about realization. I tried to find another solution instead of good well known like `ThreadLocalRandom.current()...`  and I didn't find... 
I found only `SplittableRandom` which has +- the same performance as `ThreadLocalRandom`

**Comment by Amerousful** [comment]
@shoaib42 @gemiusz Initial task didn't contain any info `Double` or any another type instead `Int` and `Long`... Nevertheless, we can generate `Double` in this way: 😅 
``` 
#{randomInt(1,10)}.#{randomInt(100,999)}
```

**Comment by shoaib42** [comment]
@Amerousful I pointed to the fact that sometimes you'll have to use the correct type. I am not a 100% sure how this would work with gRPC plugin, where the proto buff has a float and you send `#{randomInt(1,10)}.#{randomInt(100,999)}` to construct a payload. I'll find time today to try this out with the gRPC plugin. Something like having an int32 and passing the `#{currentTimeMillis()}`.

Another scenario could be the latitude, longitude generation in a given range. say for example 11.987 to 12.123 , the end user would have to juggle with this while generating with string concactination.

I'm trying to focus on the use cases and requirements, to help this effort :)

**Comment by Amerousful** [comment]
Yep, I understand. My example was just a workaround :)

**Comment by slandelle** [comment]
Re https://github.com/gatling/gatling/issues/4316#issuecomment-1215076367

That won't let you generate `3.01`.

**Comment by shoaib42** [comment]
@slandelle exactly my point, and my thoughts are gatling would see issues open up for "can we get randomDouble" etc. Just trying to avoid the misses before this roles out. The call isn't mine, just throwing out ideas :)

**Comment by slandelle** [comment]
>  randomDouble(min, max, round) | round = -1, no rounding

I really don't like magic values.
We could have `randomDouble(min, max)` and `randomDouble(min, max, fractionalDigits)`.

> randomFloat

Let's postpone this one and see if someone ever needs it.

> do you have thinking about using BigDecimal to handle all numbers ?

@gemiusz This feature is for generating HTTP payloads, not for performing scientific or financial computations. I don't think we need BigDecimal support. Just like above, I might be wrong, but let's wait for a use case to show up. YAGNI.

**Comment by Amerousful** [comment]
@shoaib42 Yep, you're totally right) 
I understand and don't deny necessity functions for random `Double` and `Float`. I just to basic on initial task which contains info only about `Int` and `Long`

**Comment by Amerousful** [comment]
@shoaib42 I think it's fair if you will implement random for `Double` :)

**Comment by shoaib42** [comment]
@Amerousful There is an edge case with rounding double. A quick hacky way is `Math.round(nextDouble(min,max) * pow(10, digits)) / pow(10, digits)`, but this can break _near_ double max value. @slandelle I'll assume that the use of randomDouble will not be used to generate values near max values or epsilon.

**Comment by slandelle** [comment]
@shoaib42 There are 2 different cases:
* `randomDouble(min, max)` => no brainer
* `randomDouble(min, max, fractionalDigits)` => your hacky way will overflow for large number or large number of digits. AFAIK, the only correct way to do that is to use `BigDecimal`, eg:

```java
double rounded = BigDecimal
      .valueOf(10.12345)
      .setScale(2, BigDecimal.ROUND_HALF_UP)
      .doubleValue();
```

And let's use the term `scale` instead of `digits` as in `BigDecimal`'s javadoc.

Does this sounds good to you?

**Comment by shoaib42** [comment]
I'm aware of the BigDecimal and can make the changes. My only concern is performance as internally it will convert to string/char array. I thought of doing string with formatter and back to double, but again I thought of performance. Should I first check what performance better? There's always a catch with floating points with precision.

**Comment by slandelle** [comment]
I suspect any correct solution would have poor performance.

Actually, this makes me wonder if this scale feature is really something we want for numbers. Shouldn't actually such generator output text? I suspect the main (sole?) usage of this generator would be to populate forms/JSON payloads.
Maybe that's something we might want to save for later, or never implement ourselves but just tell users to use dedicated libraries for advanced generators such as java-faker.
