### ISSUE TITLE
Core: Find alternative to pebble library

### ISSUE THREAD

**Issue by SatanicMechanic** [gatling/gatling#4333]
Pebble does not appear to be regularly maintained anymore, and now has a [critical vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2022-37767).  Please consider migrating to an alternative.

**Comment by slandelle** [comment]
> Pebble does not appear to be regularly maintained anymore

This is too soon to state this. The CVE seems to have been reported to the project 15 hours ago. I can't say if the reporter tried to reach out to the library authors prior to opening a CVE or if it just popped out of the blue.

> Please consider migrating to an alternative.

Before that:
* pebble is an open source project. Have you or your organization considered contributing a fix?
* have you or your organization considered investigating alternative templating engines (loops and conditional blocks support is a must) and contributing its support in Gatling?

**Comment by SatanicMechanic** [comment]
I’m not a developer but from a quick glance are open/closed issues and PRs there, it appeared that there has not been a spring boot update in a couple of years, and very minimal activity of any kind in the past year. I could be mistaken. 

I wish I could be of more help but I’m just a compliance monkey. My org does contribute to some OSS projects but I have no say in that.

**Comment by slandelle** [comment]
>  there has not been a spring boot update

Which doesn't mean this library is not compatible with more modern Spring Boot versions. And then, this library is not meant exclusively for Spring Boot (proof, we use it and have nothing to do with Spring Boot).

Now, the latest version of Pebble is compatible with Spring 6.

> very minimal activity of any kind in the past year

Activity can be erratic on every open source project with only one core maintainer. The only exception I'm aware of is Jackson. But that doesn't mean the project is broken.

**Comment by slandelle** [comment]
Now, back to the core topic.

IMO, this specific CVE is invalid. It tried to reach out [here](https://cveform.mitre.org/) twice but they never bothered replying. You should declare it as a false positive in your security tool.

Technically speaking, we could support also another library, eg [freemarker](https://freemarker.apache.org/). But I'm reluctant atm:
* as you can see, almost no one has complained about this so called CVE when using Gatling
* I'd rather avoid providing multiple ways to do the same thing, if possible. I did it with JsonPath vs JMESPath because I'm convinced that JMESPath is way superior because it's properly specified and hence mostly compatible across certified implementations.

**Comment by slandelle** [comment]
Closing for now. This CVE is a scam, even though the people managing the CVE database don't bother replying to emails.
