### ISSUE TITLE
Netty dependency not found for Gatling (via Gradle in Spring project)

### ISSUE THREAD

**Issue by MichalKotecki** [gatling/gatling#4341]
I get an error
`Could not find netty-transport-native-epoll-4.0.51.Final-linux-aarch_64.jar (io.netty:netty-transport-native-epoll:4.0.51.Final).`
when trying to include Gatling (`id "io.gatling.gradle" version "3.8."`) into my Spring Gradle project, because it uses Netty.
It seems like it could not been found in any repository, because the name is actually wrong. There is a JAR called
netty-transport-native-epoll-4.0.51.Final-linux-x86_64.jar, so what is wrong is probably the naming mistake, the required artifact should be 'x86_64', not 'aarch_64'.

Can I fix it somehow myself?

**Comment by slandelle** [comment]
This happens because you're trying to downgrade the netty version from the one Gatling uses to the one your Spring project is using. This version predates the availability of this library form ARM Linux.

Now, this is very bad. You're using Netty 4.0.51 which was released on 24-Aug-2017. 5 years ago. Netty 4.0 has reached end-of-life years ago and suffers from numerous bugs and critical security vulnerabilities.

Gatling 3.8 uses Netty 4.1.82 (yes, that's at least 82 releases between your version and the up-to-date one).

I definitely recommend against using Gatling with a downgraded Netty 4.0. I'm pretty sure it won't work and you won't be able to ask for help with the issues you'll face.

I see 2 possibilities:
* isolate your Gatling usage in a different gradle project (can be in the same repository, but in a subfolder)
* upgrade your app stack, which suffers from major CVEs

Note: this kind of questions are best asked on our community forum: https://community.gatling.io/

**Comment by MichalKotecki** [comment]
The reason why I tried to downgrade Netty to that particular version is because it is listed in the troubleshouting section of this page: https://gatling.io/docs/gatling/reference/current/extensions/gradle_plugin/

If I go with 4.1.82 I get a similar error:
`Could not find netty-transport-native-epoll-4.1.53.Final-linux-aarch_64.jar`

**Comment by slandelle** [comment]
Please don't spam multiple projects with the same question.
Already answered there: https://github.com/netty/netty/issues/12872#issuecomment-1271365797

**Comment by slandelle** [comment]
> Could not find netty-transport-native-epoll-4.1.53.Final-linux-aarch_64.jar

As I said, you have to upgrade to 4.1.82.

> The reason why I tried to downgrade Netty to that particular version is because it is listed in the troubleshouting section of this page: https://gatling.io/docs/gatling/reference/current/extensions/gradle_plugin/

I'm going to remove this block. This is a bad advice that predates the time this plugin was donated to Gatling.
