### ISSUE TITLE
Reports: Should be visible dots for injections that are made every some time in "Response Time Percentiles over Time (OK)" chart

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4342]
Gatling: 3.8.4
OS: Windows 10 Pro
JDK: jdk-17.0.4
Browser: Chrome (106.0.5249.103)

At "Response Time Percentiles over Time (OK)" chart should be visible "dots" of  injections that are made every some time.

Simulation that can be used for reproduce: [Case0014Loop5times1RPSand3sPauseSimulation](https://github.com/gemiusz/gatling-examples-maven-java/blob/master/src/test/java/pl/gemiusz/Case0014Loop5times1RPSand3sPauseSimulation.java)

Screen showing missing "dots":
![image](https://user-images.githubusercontent.com/30750006/195170878-5b679b68-db8e-4add-ab74-3e9899e073ea.png)

Screen showing "one of dot":
![image](https://user-images.githubusercontent.com/30750006/195171257-b751f737-79dd-4144-b6a5-69f1284e202d.png)

**Comment by slandelle** [comment]
Sadly, this is not something we'll be able to fix in the open-source reports.
We're using the Highstock charts library and are limited by the features it provides. We don't have full control over the generated SVG.

Here, what happens is that:
* we don't connect null values, because we want to display gaps during when there were no requests
* in your use case, you never have consecutive second plots
* Highstock only draws a line when 2 plots are connected. It doesn't draw a dot on isolated plots.

I'm closing this as this is not something we'll ever be able to fix unless we decide to ditch Highstock and completely rewrite the reports with a different library, which would be a huge effort and not something we plan on doing.

Then, if the problem arises on Gatling Enterprise, we'll be able to fix there as we use low level D3 there.
