### ISSUE TITLE
JMS: impossible to use built-in EL function `#{randomUuid()}` in JMS property

### ISSUE THREAD

**Issue by faisal6621** [gatling/gatling#4369]
When I am trying to use the [built-in function](https://gatling.io/docs/gatling/reference/current/core/session/el/#built-in-functions) `#{randomUuid()}` as:

```java
    scenario("jms")
        .exec(
            jms("message")
                .send()
                .queue("gatling")
                .textMessage("hello gatling")
                .property("random", "#{randomUuid()}")
        );
```

I am getting the following error:

```
javax.jms.MessageFormatException: Only objectified primitive objects, String, Map and List types are allowed but was: 9a2df475-05d7-0a3e-8e04-56351642b403 type: class java.util.UUID
```

I tried changing the property declaration to `.property("random", "#{randomUuid().toString()}")` but that does not work either.
```
io.gatling.core.session.el.ElParserException: Failed to parse #{randomUuid().toString()} with error ''}' expected but '.' found'
```

**Comment by slandelle** [comment]
@Amerousful Maybe it was wrong to make `randomUuid()` return a `java.util. UUID` instead of a String. WDYT?

**Comment by Isammoc** [comment]
@slandelle Shouldn't we have the `.toString()` builtin function?

**Comment by slandelle** [comment]
@Isammoc I don't think so. 

1. Gatling EL is supposed to be a **simple** templating engine, not a full blown programming language where people can be under the impression they can insert any arbitrary Java code inside `#{}`. It feels like a dangerous rabbit hole.
2. @faisal6621 only tried this because he though things should "just work". I agree with this expectation. His `.toString()` was a workaround tentative.

In order to make things "just work", we have 2 possibilities:
1. make Gatling JMS support work for any property value type

Let's appreciate the type unsafety of `javax.jms.Message#setObjectProperty`

```java
    /** Sets a Java object property value with the specified name into the 
      * message.
      *  
      * <P>Note that this method works only for the objectified primitive
      * object types ({@code Integer}, {@code Double}, 
      * {@code Long} ...) and {@code String} objects.
      *  
      * @param name the name of the Java object property
      * @param value the Java object property value to set
      *  
      * @exception JMSException if the JMS provider fails to set the property
      *                          due to some internal error.
      * @exception IllegalArgumentException if the name is null or if the name is
      *                          an empty string.
      * @exception MessageFormatException if the object is invalid
      * @exception MessageNotWriteableException if properties are read-only
      */ 
    void
    setObjectProperty(String name, Object value)
                        throws JMSException;
```

2. Make `randomUuid()` return a String instead of a `java.util.UUID`.

I'm not fond of 1 because it means type checking at runtime any parameter value and calling `toString` for anything else that numbers. As a result, we let users pass any crap and make debugging way harder.

I have the feeling that 2 is correct
* I don't feel there's any use for `java.util.UUID`. On the contrary, I think we always end up calling `toString()` in order to perform String concatenation, eg generating a JSON body or a form param.
* People are expecting the String form, not to have to deal with the `java.util.UUID` API.

**Comment by Isammoc** [comment]
@slandelle I agree with `#{randomUuid()}` should return a `String`.

But as users may store any value in session, I suggest we also add a way to transform it to something suitable to the wanted output. WDYT?

**Comment by Amerousful** [comment]
@slandelle Hm... So what do we have? ActiveMQ has the method `checkValidObject` which doesn't accept `UUID`.
Also, we don't know how many places can be (or will be) with the same problem... Nevertheless, I think we have to just call `toString` in `JmsMessage 42:64` and `JmsAction 61:75` if the type of `object` doesn't match with any type inside the `checkValidObject` function

**Comment by slandelle** [comment]
> But as users may store any value in session, I suggest we also add a way to transform it to something suitable to the wanted output. WDYT?

@Isammoc Mixed feelings:
* people don't read the documentation and try to throw anything inside `#{}`
* It's a rabbit hole. And we've already started going down in it with `jsonStringify()` and `htmlUnescape()`. You're suggesting `toString()` but what about  `base64Encoding()`, `base64Decoding()`, `substring(???)`, `regex(???)`. I'd rather wait for a real use case/feature request before introducing new ones. YAGNI.

BTW, it would be great to be able to improve error handling in the parser and have `toString() is not a valid Gatling Expression Language function, see doc url` instead of `Failed to parse #{randomUuid().toString()} with error ''}' expected but '.' found'`. I'm afraid I won't have time to tackle this myself and play with Scala parser combinators .

**Comment by slandelle** [comment]
> We can do like we accept only typeUUID (and any other type which can be produced by EL functions).

As you pointed out: are we sure those 2 places are the only ones where we would have to patch? What about other protocol supports (MQTT, third parties)?

> But still, I agree with the point that there aren't cases when a user uses "raw" UUID. Payloads in most cases are always just String

There's a consensus on this point, so let's do it. PR incoming.

**Comment by slandelle** [comment]
Other discussions are interesting then.

**Comment by Amerousful** [comment]
One moment, PR almost done

**Comment by faisal6621** [comment]
@slandelle when it is planned to release milestone [3.9.1](https://github.com/gatling/gatling/milestone/111)?

**Comment by slandelle** [comment]
In one month from now, probably.

Here, you can easily work around the issue and pass a function instead of using Gatling EL:

session -> UUID.randomUuid().toString()

**Comment by slandelle** [comment]
@faisal6621  Gatling 3.9.1 is out.
