### ISSUE TITLE
Reports: Text Only Report Option

### ISSUE THREAD

**Issue by zanfranceschi** [gatling/gatling#4532]
Hey, Gatling Team!

I'd like to propose a text only report option for the visually impaired – I guess this is a relatively simple feature to implement that would immensely help some folks (and maybe even help in a "terminal oriented" environment).

This idea came from an event that I run in which many participants execute Gatling tests. Some of them are visually impaired and they think it's really hard to read the HTML reports.

Many thanks!

**Comment by zanfranceschi** [comment]
I don't know Scala enough to contribute to Gatling code base, but if it could be done with some other lang I'd glad to help! (I know Clojure and Java which run on JVM).

**Comment by slandelle** [comment]
> I don't know Scala enough to contribute to Gatling code base
> I know Clojure and Java which run on JVM

Honestly, Java is close enough to Scala for this piece of code so that you are perfectly able to contribute to this part of the code. We're not talking about complex pieces like the WebSocket FSM.

The entry point is [here](https://github.com/gatling/gatling/blob/main/gatling-app/src/main/scala/io/gatling/app/RunResultProcessor.scala#L65).

In order to compile, you'll have to install [sbt](https://www.scala-sbt.org/) and run `sbt compile`.

**Comment by zanfranceschi** [comment]
Excellent!

**Comment by slandelle** [comment]
Closing for now due to lack of activity and interest.
