### ISSUE TITLE
Proposition of change name of script from 'start' to 'demo" in gatling-js-demo to be more accurate.

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4567]
Details: 
https://github.com/gatling/gatling-js-demo/pull/2

**Comment by slandelle** [comment]
Actually, this issue is that we've changed the commands before the official release and forgot to update the README.
Whatever alias the user wants to create in his npm conf is up to him.
We should only emphasize the underlying commands and be consistent with the documentation: https://docs.gatling.io/tutorials/scripting-intro-js/#run-the-simulation-locally
